'use client';
import Link from 'next/link';
import {useState} from 'react';
import {ChevronDown,LayoutDashboard,LogOut,Menu,Search,Settings} from 'lucide-react';

type Item=[string,string];
type Group=[string,Item[]];
const I=(label:string,slug:string):Item=>[label,slug];
const G=(label:string,items:Item[]):Group=>[label,items];
const menus:Record<string,{label:string;title:string;groups:Group[]}>= {
 superadmin:{label:'SUPER ADMIN',title:'Master Control',groups:[G('Command Center',[I('Overview','dashboard'),I('Live Operations','operations'),I('Alerts & Approvals','approvals')]),G('Identity & Access',[I('User Master','users'),I('Roles & Permissions','roles'),I('Admin Accounts','admins'),I('Sessions & Devices','sessions')]),G('Masters',[I('City Master','cities'),I('Developer Master','developers'),I('Property / Asset Master','assets'),I('Asset Allocation','allocations')]),G('Policy & Lifecycle',[I('Policy Creation Engine','policy-engine'),I('Proposal Queue','proposals'),I('Policy Book','policies'),I('Lifecycle Manager','lifecycle'),I('Rules Engine','rules')]),G('KYC & Customer',[I('KYC Approval Queue','kyc'),I('User / KYC Master','kyc-users'),I('Bank Verification','bank-verification'),I('Nominee Management','nominees'),I('Address Verification','address-verification'),I('Ownership Transfer','ownership')]),G('Financial Core',[I('Central Ledger','ledger'),I('EMI Collection','emi-collection'),I('Reconciliation','reconciliation'),I('Adjustments & Reversals','adjustments'),I('Refund & Settlement','settlements')]),G('Yield & Payouts',[I('Yield Engine','yield'),I('Payout Queue','payouts'),I('Failed Payouts','failed-payouts'),I('Yield Forecast','yield-forecast')]),G('Agents & Commission',[I('Agent Master','agents'),I('Hierarchy','hierarchy'),I('Commission Engine','commission'),I('Commission Holds','commission-holds'),I('Clawbacks','clawbacks'),I('Performance Analytics','agent-performance')]),G('Documents & Dispatch',[I('Document Center','documents'),I('Print Queue','print-queue'),I('Courier / AWB','courier'),I('Delivery Tracking','delivery'),I('Reprint Requests','reprints')]),G('Support & Grievance',[I('Ticket Queue','support'),I('SLA Monitor','sla'),I('Escalations','escalations'),I('Resolution History','resolution-history')]),G('Reports & Security',[I('MIS Reports','reports'),I('Audit Logs','audit'),I('Security Events','security-events'),I('Webhook Events','webhooks'),I('Job Queues','jobs')]),G('Platform Control',[I('Notifications','notifications'),I('Integrations','integrations'),I('Feature Flags','feature-flags'),I('System Settings','system-settings')])]},
 opsadmin:{label:'OPS ADMIN',title:'Operations Workspace',groups:[G('Operations',[I('Dashboard','dashboard'),I('Approvals','approvals'),I('Policies','policies'),I('Lifecycle','lifecycle'),I('EMI Collection','emi-collection'),I('Reconciliation','reconciliation')]),G('Customers',[I('Users','users'),I('KYC Queue','kyc'),I('Bank Verification','bank-verification'),I('Nominee','nominees'),I('Address Verification','address-verification')]),G('Assets & Partners',[I('Cities','cities'),I('Developers','developers'),I('Assets','assets'),I('Allocations','allocations')]),G('Financial',[I('Ledger','ledger'),I('Yield','yield'),I('Payouts','payouts'),I('Settlements','settlements')]),G('Documents & Support',[I('Documents','documents'),I('Print Queue','print-queue'),I('Courier','courier'),I('Support','support'),I('Reports','reports')])]},
 supportadmin:{label:'SUPPORT ADMIN',title:'Support Command Center',groups:[G('Support',[I('Dashboard','dashboard'),I('Ticket Queue','support'),I('SLA Monitor','sla'),I('Escalations','escalations'),I('Resolution History','resolution-history')]),G('Customer Context',[I('Users','users'),I('Policies','policies'),I('Payments','payments'),I('Documents','documents')]),G('Communications',[I('Notifications','notifications'),I('Broadcasts','broadcasts'),I('Templates','templates')])]},
 kycadmin:{label:'KYC ADMIN',title:'KYC Verification Desk',groups:[G('KYC',[I('Dashboard','dashboard'),I('Approval Queue','kyc'),I('User Master','kyc-users'),I('Bank Verification','bank-verification'),I('Address Verification','address-verification'),I('Nominee Management','nominees')]),G('Policy Context',[I('Policies','policies'),I('Proposals','proposals'),I('Exceptions','exceptions')]),G('Audit',[I('Verification Audit','audit'),I('Reports','reports')])]},
 agent:{label:'FIELD SALES',title:'Agent Workspace',groups:[G('Home',[I('Dashboard','dashboard'),I('My Performance','performance'),I('HO Notices','notices')]),G('Sales & Clients',[I('Client Registry','clients'),I('New Proposal','proposal'),I('Proposal Queue','proposal-queue'),I('Policies','policies')]),G('Collections',[I('EMI Follow-up','emi'),I('Payment Links','payment-links'),I('Missed EMI Alerts','missed-emis'),I('Follow-up Tasks','follow-ups'),I('Lapse Warnings','lapse-warnings')]),G('Money',[I('Commission','commission'),I('TDS Statements','tds'),I('Payout Statements','payouts')]),G('Help',[I('Support','support'),I('Profile','profile')])]},
 user:{label:'POLICYHOLDER',title:'My DISH',groups:[G('Home',[I('Dashboard','dashboard'),I('My Policy','policy')]),G('Money',[I('Payments & EMI','payments'),I('Yield & Benefits','yield'),I('Payout Tracking','payout-tracking')]),G('Documents',[I('Document Center','documents'),I('EMI Receipts','receipts'),I('Annual Statements','statements'),I('Tax / Income Summary','tax-summary')]),G('Requests',[I('Nominee Update','nominee-request'),I('Bank Change','bank-request'),I('Address Update','address-request'),I('Termination Request','termination')]),G('Help & Security',[I('Support / Grievance','support'),I('Profile & Security','profile')])]}
};
function routeFor(role:string,slug:string){return `/${role==='superadmin'?'admin':role==='user'?'user':role}/${slug}`}
function Brand(){return <Link href="/" className="brand"><span className="mark"><i/></span><span>DISH</span></Link>}
export function PortalShell({role,slug,children}:{role:string;slug:string;children:React.ReactNode}){const m=menus[role]||menus.superadmin;const [open,setOpen]=useState(false);return <div className="layout"><aside className="side"><Brand/><div className="sideKicker">{m.label}</div><h2>{m.title}</h2><nav className="nav">{m.groups.map(([group,items])=><div key={group}><div className="navGroup">{group}</div>{items.map(([label,itemSlug])=><Link className={slug===itemSlug?'active':''} href={routeFor(role,itemSlug)} key={itemSlug}><LayoutDashboard size={15}/>{label}</Link>)}</div>)}</nav><button className="sideLogout" onClick={()=>{localStorage.removeItem('dish_session');location.href='/'}}><LogOut size={15}/> Sign out</button></aside><div className="mobileTop"><button className="mobileMenuBtn" onClick={()=>setOpen(!open)}><Menu size={17}/>{m.label}<ChevronDown size={14}/></button>{open&&<div className="mobileMenu">{m.groups.map(([group,items])=><div key={group}><div className="mobileGroup">{group}</div>{items.map(([label,itemSlug])=><Link href={routeFor(role,itemSlug)} onClick={()=>setOpen(false)} key={itemSlug}><LayoutDashboard size={15}/>{label}</Link>)}</div>)}<button className="mobileSignout" onClick={()=>{localStorage.removeItem('dish_session');location.href='/'}}><LogOut size={15}/> Sign out</button></div>}</div><main className="main"><div className="topbar"><div className="topBrand"><Brand/><span className="roleTag">{m.label}</span></div><div className="headRight"><div className="search"><Search size={15}/><input placeholder="Search this workspace"/></div><button className="iconBtn"><Settings size={17}/></button><div className="avatar">{role==='user'?'DU':role==='agent'?'AG':'SA'}</div></div></div>{children}</main></div>}
export {menus};
