'use client';
import RolePortalScreen from './RolePortalScreen';
import {PortalShell} from './PortalShell';
const MAP:any={
admin:{operations:'live-operations',approvals:'alerts-approvals',users:'user-master',roles:'roles-permissions',admins:'admin-accounts',sessions:'sessions-devices',cities:'city-master',developers:'developer-master',assets:'property-asset-master',allocations:'asset-allocation','policy-engine':'policy-creation-engine',proposals:'proposal-queue',policies:'policy-book',lifecycle:'lifecycle-manager',rules:'rules-engine',kyc:'kyc-approval-queue','kyc-users':'user-kyc-master','bank-verification':'bank-verification',nominees:'nominee-management','address-verification':'address-verification',ownership:'ownership-transfer',ledger:'central-ledger','emi-collection':'emi-collection',reconciliation:'reconciliation',adjustments:'adjustments-reversals',settlements:'refund-settlement',yield:'yield-engine',payouts:'payout-queue','failed-payouts':'failed-payouts','yield-forecast':'yield-forecast',agents:'agent-master',hierarchy:'hierarchy',commission:'commission-engine','commission-holds':'commission-holds',clawbacks:'clawbacks','agent-performance':'performance-analytics',documents:'document-center','print-queue':'print-queue',courier:'courier',delivery:'delivery-tracking',reprints:'reprint-requests',support:'ticket-queue',sla:'sla-monitor',escalations:'escalations','resolution-history':'resolution-history',reports:'mis-reports',audit:'audit-logs','security-events':'security-events',webhooks:'webhook-events',jobs:'job-queues',notifications:'notifications',integrations:'integrations','feature-flags':'feature-flags','system-settings':'system-settings'},
opsadmin:{approvals:'approvals',policies:'policies',lifecycle:'lifecycle','emi-collection':'emi-collection',reconciliation:'reconciliation',users:'users',kyc:'kyc-queue','bank-verification':'bank-verification',nominees:'nominee','address-verification':'address-verification',cities:'cities',developers:'developers',assets:'assets',allocations:'allocations',ledger:'ledger',yield:'yield',payouts:'payouts',settlements:'settlements',documents:'documents','print-queue':'print-queue',courier:'courier',support:'support',reports:'reports'},
supportadmin:{support:'ticket-queue',sla:'sla-monitor',escalations:'escalations','resolution-history':'resolution-history',users:'users',policies:'policies',payments:'payments',documents:'documents',notifications:'notifications',broadcasts:'broadcasts',templates:'templates'},
kycadmin:{kyc:'approval-queue','kyc-users':'user-master','bank-verification':'bank-verification','address-verification':'address-verification',nominees:'nominee-management',policies:'policies',proposals:'proposals',exceptions:'exceptions',audit:'verification-audit',reports:'reports'},
agent:{performance:'my-performance',notices:'ho-notices',clients:'client-registry',proposal:'new-proposal','proposal-queue':'proposal-queue',policies:'policies',emi:'emi-follow-up','payment-links':'payment-links','missed-emis':'missed-emi-alerts','follow-ups':'follow-up-tasks','lapse-warnings':'lapse-warnings',commission:'commission',tds:'tds-statements',payouts:'payout-statements',support:'support',profile:'profile'}
};
export default function RolePortalRoute({role,slug}:{role:string;slug:string}){const mapped=(MAP[role]||{})[slug]||slug;return <PortalShell role={role} slug={slug}><RolePortalScreen role={role} slug={mapped}/></PortalShell>}
