'use client';

export type ScreenCatalog={
  view:'dashboard'|'table'|'queue'|'detail'|'form'|'chart'|'timeline'|'settings';
  title:string; sub:string; kpis:string[]; values:string[]; columns:string[]; rows:string[][]; actions:string[]; note:string;
};

const c=(title:string,sub:string,view:ScreenCatalog['view'],kpis:string[],values:string[],columns:string[],rows:string[][],actions:string[],note:string):ScreenCatalog=>({title,sub,view,kpis,values,columns,rows,actions,note});

export const screenCatalog:Record<string,ScreenCatalog>={
  hierarchy:c('Agent Hierarchy','Inspect reporting lines, city mapping and policy ownership across the field network.','detail',['Agents','Managers','Cities','Unmapped'],['248','18','38','6'],['Node','Manager','City','Policies','State'],[['AG-2041','RM-018','Mumbai','42','Active'],['AG-1182','RM-011','Pune','31','Active'],['AG-0901','RM-004','Delhi','18','Review']],['Open hierarchy','Reassign','Audit mapping'],'Hierarchy controls reporting relationships and operational ownership.'),
  'commission-holds':c('Commission Holds','Review commissions paused because of lapse, exception, KYC or reconciliation conditions.','queue',['On hold','Lapse holds','KYC holds','Value'],['17','8','5','₹2.1L'],['Agent','Policy','Commission','Reason','State'],[['AG-2041','IREC-00821','₹3,600','EMI lapse','Hold'],['AG-1182','IREC-00791','₹2,400','KYC exception','Hold'],['AG-0901','IREC-00688','₹1,800','Reconciliation','Review']],['Review hold','Release','Keep hold'],'Commission release is controlled by policy lifecycle and exception state.'),
  clawbacks:c('Commission Clawbacks','Manage commission reversals triggered by lapse, termination or correction events.','queue',['Open','Approved','Recovered','Value'],['9','6','14','₹86K'],['Case','Agent','Original','Clawback','Reason'],[['CLB-221','AG-2041','₹3,600','₹3,600','Policy lapse'],['CLB-218','AG-1182','₹2,400','₹1,200','Settlement correction']],['Review case','Approve clawback','Mark recovered'],'Clawbacks preserve the original commission reference and recovery reason.'),
  'yield-forecast':c('Yield Forecast','Project benefit liability by policy cohort, maturity window and expected payout period.','chart',['Cohorts','12-mo liability','Long-term','Exceptions'],['42','₹7.6Cr','Dynamic','3'],['Cohort','Policies','Corpus','Projected yield'],[['2026 cohort','1,842','₹18.4Cr','₹2.21Cr'],['2027 cohort','1,602','₹16.1Cr','₹1.93Cr'],['Matured window','602','₹6.2Cr','₹0.74Cr']],['Run forecast','Stress test','Export forecast'],'Forecasts are projections for operational planning, not a payment mutation.'),
  'agent-master':c('Agent Master','Manage field-agent identity, activation, hierarchy, city mapping and operational status.','table',['Agents','Active','Pending approval','Suspended'],['248','231','11','6'],['Agent','Name','City','Hierarchy','Status'],[['AG-2041','Aarav Sales','Mumbai','RM-018','Active'],['AG-1182','Diya Finance','Pune','RM-011','Pending'],['AG-0901','Kabir Investments','Delhi','RM-004','Suspended']],['Open agent','Approve onboarding','Suspend'],'Agent master is separate from commission and hierarchy operations.'),
  'mis-reports':c('MIS Reports','Generate management reports across policy, EMI, KYC, yield, payout and agent operations.','chart',['Report packs','Scheduled','Generated today','Exceptions'],['18','7','42','2'],['Report','Scope','Owner','Generated','State'],[['Policy MIS','All cities','HO','09:30','Ready'],['EMI MIS','Current day','Finance','09:15','Ready'],['Agent MIS','Current month','Sales','08:45','Ready']],['Build report','Schedule','Export'],'MIS output is read/reporting oriented and separate from audit logs.'),
  'audit-logs':c('Audit Logs','Immutable activity review for sensitive administrative and operational actions.','timeline',['Events today','Sensitive','Reviewed','Open'],['12,481','384','361','23'],['Event','Actor','Module','Action','Time'],[['AUD-98121','SA-001','Refund','Approve','09:42'],['AUD-98120','OP-014','EMI','Retry mandate','09:40'],['AUD-98119','KY-006','KYC','Approve','09:37']],['Inspect event','Filter actor','Export audit'],'Audit review records who performed a sensitive action and when.'),
  'security-events':c('Security Events','Investigate authentication, access-control and suspicious session events.','timeline',['Events','High risk','Blocked','Open investigations'],['482','7','18','3'],['Event','Actor','Type','Location','Risk'],[['SEC-2201','OP-014','New device','Pune','Low'],['SEC-2198','SA-001','Privilege change','Mumbai','High'],['SEC-2197','Unknown','Login anomaly','Unknown','High']],['Investigate','Revoke access','Export evidence'],'Security events are distinct from ordinary audit activity.'),
  'webhook-events':c('Webhook Events','Inspect inbound gateway, banking, messaging and courier callbacks with processing status.','table',['Received','Processed','Failed','Retries'],['4,821','4,798','23','11'],['Event','Provider','Reference','State','Received'],[['WH-8211','Razorpay','PAY-8821','Processed','09:41'],['WH-8210','Bank API','BNK-2201','Processed','09:39'],['WH-8209','Courier','AWB-7712','Failed','09:38']],['Inspect payload','Retry event','Mark resolved'],'Webhook processing must be idempotent and auditable server-side.'),
  'job-queues':c('Job Queues','Monitor asynchronous print, notification, payout, reconciliation and document jobs.','table',['Running','Queued','Failed','Delayed'],['18','42','3','2'],['Job','Queue','Owner','Age','State'],[['JOB-8821','Payout','Finance','2m','Running'],['JOB-8819','Print','Dispatch','8m','Queued'],['JOB-8818','Notification','Support','11m','Failed']],['Inspect job','Retry failed','Assign owner'],'Queue operations are separated from the business records they process.'),
  notifications:c('Notifications','Control customer and internal notification delivery across SMS, WhatsApp, email and in-app channels.','table',['Queued','Sent today','Failed','Templates'],['84','2,481','19','36'],['Message','Channel','Recipient','Purpose','State'],[['NTF-8821','SMS','Aarav Mehta','EMI reminder','Sent'],['NTF-8819','WhatsApp','Diya Shah','Payment link','Queued'],['NTF-8818','Email','Kabir Rao','Policy document','Failed']],['Send test','Retry failed','Open template'],'Notification operations are delivery-focused and auditable.'),
  integrations:c('Integrations','Monitor external provider connectivity for payments, banking, messaging, storage and courier services.','settings',['Providers','Connected','Degraded','Webhooks'],['8','7','1','42'],['Provider','Purpose','Health','Last check'],[['Razorpay','Payments','Connected','1m'],['Bank API','Verification','Connected','2m'],['MSG91','SMS','Degraded','3m'],['S3 / R2','Documents','Connected','1m']],['Test connection','View events','Rotate config'],'Provider health is operational configuration, not a customer record.'),
  'feature-flags':c('Feature Flags','Control staged rollout of platform capabilities by role, portal and environment.','settings',['Flags','Enabled','Pilot','Off'],['28','19','5','4'],['Flag','Scope','Rollout','State'],[['New KYC viewer','KYC Admin','100%','Enabled'],['Payout retry v2','Ops Admin','25%','Pilot'],['New agent analytics','Agent','0%','Off']],['Edit rollout','Enable pilot','Audit change'],'Feature changes require controlled review and audit.'),
  'system-settings':c('System Settings','Platform-wide configuration with sensitive-change review and environment awareness.','settings',['Settings','Sensitive','Pending changes','Last deploy'],['86','14','3','Today 08:20'],['Setting','Scope','Current','Risk'],[['EMI retry window','Financial','48h','High'],['Session timeout','Security','30m','Medium'],['Document retention','Storage','7y','High']],['Edit setting','Review change','View audit'],'Sensitive settings should be protected by RBAC and server-side authorization.'),
  'print-queue':c('Print Queue','Manage policy bonds, receipts, annual statements and other print-ready document packets.','queue',['Queued','Printing','Failed','Today'],['84','12','3','126'],['Packet','Document','Policy','Printer','State'],[['PRN-8821','Policy Bond','IREC-00841','PR-02','Queued'],['PRN-8819','Annual Statement','IREC-00840','PR-01','Printing'],['PRN-8818','EMI Receipt','IREC-00839','PR-03','Failed']],['Open packet','Retry print','Dispatch'],'Print operations are separated from document generation and delivery tracking.'),
  courier:c('Courier / AWB','Create and track dispatch packets, courier assignments and airway bill references.','table',['Ready','Dispatched','In transit','Exceptions'],['31','18','27','2'],['Packet','AWB','Courier','Destination','State'],[['PKT-8821','AWB771288','BlueDart','Mumbai','In transit'],['PKT-8819','AWB771201','Delhivery','Pune','Dispatched']],['Create AWB','Dispatch','Open tracking'],'Courier control manages physical document movement.'),
  'delivery-tracking':c('Delivery Tracking','Track document delivery milestones from dispatch through recipient confirmation.','timeline',['In transit','Delivered','Delayed','Returned'],['27','184','4','2'],['AWB','Policy','Milestone','Last scan','State'],[['AWB771288','IREC-00841','Hub Mumbai','09:21','In transit'],['AWB771201','IREC-00840','Delivered','Yesterday','Delivered'],['AWB771177','IREC-00839','No scan','2d','Delayed']],['Track packet','Mark delivered','Open exception'],'Delivery status is distinct from print queue and courier assignment.'),
  'reprint-requests':c('Reprint Requests','Review customer or operations requests for duplicate policy and financial documents.','queue',['Pending','Approved','Printing','Rejected'],['12','8','3','1'],['Request','Policy','Document','Reason','State'],[['RPR-2201','IREC-00841','Policy Bond','Lost original','Pending'],['RPR-2198','IREC-00840','Annual Statement','Damaged','Approved']],['Review request','Approve reprint','Reject'],'Reprints require a reason and controlled approval.'),
  'ticket-queue':c('Ticket Queue','Prioritized support case workspace with SLA, ownership, category and escalation state.','queue',['Open','SLA risk','Escalated','Unassigned'],['38','7','3','4'],['Ticket','Customer','Category','Owner','SLA'],[['TKT-8821','Aarav Mehta','EMI','Support L1','18h'],['TKT-8818','Diya Shah','Policy','Support L2','4h'],['TKT-8811','Kabir Rao','Documents','Unassigned','22h']],['Open ticket','Assign','Escalate'],'Ticket operations track ownership and SLA separately from customer records.'),
  'sla-monitor':c('SLA Monitor','Monitor response and resolution clocks across support tiers and escalated cases.','chart',['Open','At risk','Breached','Resolved today'],['38','7','2','31'],['Tier','Cases','Target','Breached','State'],[['L1','24','24h','1','Watch'],['L2','8','8h','1','Watch'],['L3','3','4h','0','Healthy']],['Open breach','Reassign','Export SLA'],'SLA monitoring drives escalation without changing the underlying case automatically.'),
  escalations:c('Escalations','Review cases moving from Support Admin to Ops Admin and Super Admin.','timeline',['Open','Ops level','Super Admin','Resolved'],['6','4','2','31'],['Case','Current owner','Level','Reason','Age'],[['ESC-8821','Ops Admin','L2','Payment dispute','18h'],['ESC-8818','Super Admin','L3','Refund exception','9h']],['Escalate','Reassign','Resolve'],'Escalation path is Support Admin → Ops Admin → Super Admin.'),
  'resolution-history':c('Resolution History','Search closed grievances, actions taken, approvals and customer communication history.','timeline',['Resolved','This week','Reopened','Avg resolution'],['214','214','4','7.2h'],['Ticket','Category','Resolution','Owner','Closed'],[['TKT-8711','EMI','Payment reconciled','Ops Admin','Today'],['TKT-8684','Document','Reissued bond','Support Admin','Yesterday']],['Open case','View communication','Export history'],'Resolution history is a traceable record of support outcomes.'),
  'live-operations':c('Live Operations','Real-time operational queues and processing health across DISH services.','table',['Jobs running','Queues waiting','Failed jobs','SLA breaches'],['18','42','3','2'],['Queue','Owner','Waiting','State'],[['EMI collection','Finance','12','Running'],['KYC verification','KYC','8','Running'],['Document print','Dispatch','17','Queued'],['Payout batch','Finance','5','Review']],['Inspect queue','Retry failed','Assign owner'],'Operations health is a live queue workspace, not a summary dashboard.'),
  'central-ledger':c('Central Ledger','Authoritative transaction view for policy and financial movements.','table',['Entries today','Credits','Debits','Exceptions'],['1,284','₹22.8L','₹18.4L','3'],['Reference','Account','Debit','Credit','State'],[['LED-9921','IREC-00841','₹0','₹10,000','Posted'],['LED-9920','AG-2041','₹0','₹3,600','Posted'],['LED-9919','SET-442','₹18,000','₹0','Review']],['Open entry','Post adjustment','Reconcile'],'Financial operations require auditable, idempotent server-side processing in production.'),
  'yield-engine':c('Yield Engine','Monthly yield calculation and long-term projection controls.','chart',['Policies eligible','Monthly liability','Queued','Exceptions'],['0','₹0','0','0'],['Period','Corpus','Rate','Projected yield'],[['Year 1','₹3.6L','12%','₹43,200'],['Year 10','Dynamic','Projected','Growth'],['Year 40','Dynamic','Projected','Long-term']],['Run preview','Validate batch','View liability'],'Yield calculation is a controlled financial workflow; this UI is preview-only.'),
  'user-master':c('User Master','Search and maintain policyholder identity, access and lifecycle state.','table',['Total users','Active','KYC pending','Blocked'],['5,284','4,812','82','17'],['User ID','Name','City','KYC','State'],[['USR-10082','Aarav Mehta','Mumbai','Verified','Active'],['USR-10081','Diya Shah','Pune','Pending','Pending'],['USR-10080','Kabir Rao','Bengaluru','Verified','Active']],['Open profile','Verify KYC','Change status'],'Identity records are distinct from policy records.'),
  'roles-permissions':c('Roles & Permissions','RBAC matrix for portal access and sensitive actions.','settings',['Roles','Permissions','Sensitive actions','Recent changes'],['8','146','23','12'],['Role','Scope','Sensitive access','Updated'],[['Super Admin','Global','Full','Today'],['Ops Admin','Operations','Financial approval','Today'],['KYC Admin','KYC','Identity override','Yesterday'],['Support Admin','Support','Escalation','Yesterday']],['Create role','Edit matrix','Audit changes'],'Permission changes require explicit review and audit.'),
  'admin-accounts':c('Admin Accounts','Manage internal administrator identities, status and access.','table',['Accounts','Active','Suspended','Invites'],['28','25','1','2'],['Admin ID','Role','Last login','Status'],[['SA-001','Super Admin','Today 09:12','Active'],['OP-014','Ops Admin','Today 08:48','Active'],['KY-006','KYC Admin','Yesterday','Active'],['SU-009','Support Admin','3 days ago','Suspended']],['Invite admin','Suspend','Reset access'],'Administrative accounts are separate from policyholder users.'),
  'sessions-devices':c('Sessions & Devices','Security view of active administrator sessions and trusted devices.','table',['Active sessions','New today','Revoked','Risk flagged'],['34','8','4','2'],['Session','Admin','Device','Location','Risk'],[['SES-9921','SA-001','Chrome / Windows','Mumbai','Low'],['SES-9917','OP-014','Android','Pune','Low'],['SES-9902','KY-006','Chrome / macOS','Unknown','High']],['Revoke','Investigate','Mark trusted'],'Session controls are security operations, not profile editing.'),
  'city-master':c('City Master','Maintain supported operating cities and policy allocation metadata.','table',['Cities','Active','Draft','Restricted'],['38','35','2','1'],['City','Code','Asset count','State'],[['Mumbai','MUM','42','Active'],['Pune','PUN','26','Active'],['Bengaluru','BLR','31','Active'],['Jaipur','JAI','12','Draft']],['Add city','Edit city','Restrict'],'City records feed asset and agent mapping.'),
  'developer-master':c('Developer Master','Developer and partner registry with exposure and compliance status.','table',['Developers','Active','Under review','Blocked'],['24','20','3','1'],['Developer','Projects','Exposure','Compliance'],[['Aster Realty','8','₹42Cr','Verified'],['Northstar Infra','5','₹28Cr','Verified'],['Greenline Homes','4','₹19Cr','Review']],['Add developer','Open exposure','Review compliance'],'Developer data is partner master data, not customer data.'),
  'property-asset-master':c('Property / Asset Master','Inventory of eligible real-estate assets and valuation metadata.','table',['Assets','Allocated','Available','Review'],['143','118','19','6'],['Asset','Developer','City','Value','Availability'],[['AST-001','Aster Realty','Mumbai','₹12.4Cr','Available'],['AST-002','Northstar Infra','Pune','₹8.2Cr','Allocated'],['AST-003','Greenline Homes','Bengaluru','₹10.6Cr','Review']],['Create asset','Edit valuation','Allocate'],'Asset master holds inventory and valuation state.'),
  'asset-allocation':c('Asset Allocation','Allocate eligible assets to policy/corpus exposure.','queue',['Unallocated','Allocated','Awaiting review','Exposure'],['19','118','6','₹286Cr'],['Asset','Policy pool','Value','Requested','State'],[['AST-001','Pool MUM-04','₹12.4Cr','Today','Ready'],['AST-003','Pool BLR-02','₹10.6Cr','Yesterday','Review'],['AST-017','Pool PUN-03','₹8.9Cr','Yesterday','Allocated']],['Allocate','Hold','View exposure'],'Allocation decisions affect the asset-to-policy exposure map.'),
  'policy-creation-engine':c('Policy Creation Engine','Configure and validate policy creation from approved proposals.','form',['Rules loaded','Drafts','Validation errors','Created today'],['12','9','2','31'],['Rule','Value','Enforced at','Status'],[['Minimum EMI','₹5,000','Proposal','Active'],['Tenure','24–48 months','Proposal','Active'],['Yield option','Lock at Month 24','Lifecycle','Active']],['Validate','Create policy','Preview bond'],'Policy creation follows proposal, KYC and first-EMI activation controls.'),
  'policy-book':c('Policy Book','Search activated policy records and contractual document state.','detail',['Active books','EMI running','EMI completed','Matured'],['4,812','4,210','602','0'],['Policy','Holder','EMI','Progress','Lifecycle'],[['IREC-2024-00841','Aarav Mehta','₹10,000','18/36','EMI running'],['IREC-2024-00840','Diya Shah','₹15,000','24/24','EMI completed']],['Open policy','Download bond','View schedule'],'Policy Book is the operational record of activated policies.'),
  'rules-engine':c('Rules Engine','View and test hard policy rules before production execution.','settings',['Rules','Blocking rules','Warnings','Last validation'],['18','7','11','2m ago'],['Rule','Threshold','Enforcement','Status'],[['Minimum EMI','₹5,000','Block','Active'],['Minimum tenure','24 months','Block','Active'],['Maximum tenure','48 months','Block','Active'],['3-month lapse','3 failures','Auto-lapse','Active']],['Test rules','Edit rule','View audit'],'Hard rules from the specification are represented explicitly.'),
  'kyc-approval-queue':c('KYC Approval Queue','Side-by-side verification workbench for customer identity documents.','queue',['Pending','Low risk','Escalated','Rejected'],['82','61','7','6'],['Case','Customer','Documents','Risk','Decision'],[['KYC-821','Aarav Mehta','PAN + Aadhaar + selfie','Low','Review'],['KYC-820','Diya Shah','Aadhaar + address','Medium','Review'],['KYC-819','Kabir Rao','PAN + selfie','Low','Approved']],['Open documents','Approve','Request clarification'],'The verification workbench keeps identity evidence and decision separate.'),
  'user-kyc-master':c('User / KYC Master','Unified customer identity and verification record.','detail',['Verified','Pending','Review','Rejected'],['1,148','82','17','6'],['Case','Customer','PAN','Aadhaar','State'],[['KYC-821','Aarav Mehta','Verified','Verified','Verified'],['KYC-820','Diya Shah','Verified','Pending','Review']],['Open KYC','Request proof','Override with audit'],'KYC status is kept separate from the broader user master.'),
  'nominee-management':c('Nominee Management','View and control nominee details attached to each policy.','table',['Policies with nominee','Pending changes','Exceptions','Verified'],['4,812','18','2','4,792'],['Policy','Holder','Nominee','Relationship','State'],[['IREC-00841','Aarav Mehta','Priya Mehta','Spouse','Verified'],['IREC-00840','Diya Shah','Riya Shah','Sister','Pending']],['Open nominee','Approve change','Flag exception'],'Nominee records are policy-linked and auditable.'),
  'address-verification':c('Address Verification','Cross-check identity/address evidence against registered addresses.','queue',['Pending','Matched','Mismatch','Manual review'],['17','1,102','9','6'],['Case','Customer','Evidence','Match','State'],[['ADR-481','Aarav Mehta','Aadhaar','Matched','Verified'],['ADR-480','Diya Shah','Utility bill','Mismatch','Review']],['Open proof','Verify','Request new proof'],'Address verification is a distinct KYC operation.'),
  'ownership-transfer':c('Ownership Transfer','Transfer policy ownership for legal and succession workflows.','queue',['Requests','Legal review','Approved','Rejected'],['6','3','2','1'],['Case','Policy','Current holder','New holder','State'],[['OWN-018','IREC-00841','Aarav Mehta','Priya Mehta','Legal review'],['OWN-017','IREC-00791','Rohan Shah','Neha Shah','Approved']],['Open case','Approve transfer','Request legal proof'],'Ownership transfer requires explicit evidence review.'),
  'emi-collection':c('EMI Collection','Daily collection operations, failures and recovery routes.','table',['Due today','Collected','Failed','Recovery'],['126','118','8','₹1.2L'],['Policy','Holder','Due','Method','State'],[['IREC-00841','Aarav Mehta','₹10,000','NACH','Paid'],['IREC-00840','Diya Shah','₹15,000','NACH','Failed'],['IREC-00839','Kabir Rao','₹20,000','Manual','Pending']],['Collect','Retry mandate','Send payment link'],'Collection is distinct from ledger and reconciliation.'),
  reconciliation:c('Reconciliation','Match gateway and bank events against internal financial records.','table',['Unmatched','Matched','Exceptions','Last run'],['14','1,842','3','09:40'],['Batch','Source','Records','Variance','State'],[['REC-220','Razorpay','482','₹0','Matched'],['REC-219','Bank','721','₹2,400','Exception'],['REC-218','Smart Collect','639','₹0','Matched']],['Run reconciliation','Open exception','Export'],'Reconciliation identifies mismatches between external events and the ledger.'),
  'adjustments-reversals':c('Adjustments & Reversals','Controlled financial corrections with reason and original reference.','queue',['Pending','Approved','Reversed','High value'],['7','21','4','3'],['Reference','Original','Adjustment','Reason','State'],[['ADJ-882','LED-9919','₹18,000','Settlement correction','Pending'],['REV-221','LED-9811','₹3,600','Clawback','Approved']],['Review','Approve','Reverse'],'Every adjustment carries an explicit reason and original reference.'),
  'refund-settlement':c('Refund & Settlement','Calculate and approve termination settlement amounts.','detail',['Pending settlements','Cooling-off','Approved','Paid'],['12','2','7','31'],['Policy','Paid EMIs','Deductions','Refundable','State'],[['IREC-00821','₹90,000','₹0','₹90,000','Cooling-off'],['IREC-00791','₹120,000','₹8,000','₹112,000','Approved']],['Calculate','Approve settlement','Release payout'],'Settlement includes cooling-off, deductions and refundable amount.'),
  'payout-queue':c('Payout Queue','Approve monthly benefit payouts before gateway submission.','queue',['Queued','Approved','Processing','Value'],['42','31','8','₹4.8L'],['Payout','Policy','Amount','Gateway','State'],[['PAY-8821','IREC-00841','₹3,600','Razorpay','Queued'],['PAY-8820','IREC-00840','₹5,400','Razorpay','Approved']],['Open payout','Approve payout','Hold'],'Payout approval precedes gateway submission.'),
  'failed-payouts':c('Failed Payouts','Inspect gateway failures and prepare controlled retry or escalation.','queue',['Failed','Retryable','Bank issues','Value'],['4','3','2','₹42K'],['Payout','Policy','Reason','Attempt','State'],[['PAY-8812','IREC-00821','Bank timeout','2','Retryable'],['PAY-8809','IREC-00791','Invalid account','1','Correction']],['Inspect failure','Retry payout','Escalate'],'Failed payout handling is distinct from the normal payout queue.'),
  'performance-analytics':c('Performance Analytics','Review agent acquisition, EMI realization, commission and target performance.','chart',['Policies','EMI realization','Commission','Target'],['42','96.4%','₹2.84L','82%'],['Metric','Current','Target','Variance'],[['Policies','42','50','-8'],['EMI realization','96.4%','95%','+1.4%'],['Commission','₹2.84L','₹3L','-₹16K']],['Open drilldown','Compare period','Export'],'Performance analytics combines field activity and financial outcomes.'),
  'document-center':c('Document Center','Control policy bonds, trackers, statements, receipts, tax and benefit documents.','table',['Document types','Ready','Queued','Exceptions'],['10','1,842','84','3'],['Document','Policy','Type','Generated','State'],[['DOC-8821','IREC-00841','Policy Bond','05 Sep','Ready'],['DOC-8819','IREC-00840','Annual Statement','05 Sep','Ready']],['Open document','Generate','Download'],'The document center covers the documented policyholder document set.'),
  'support':c('Support Workspace','Handle support cases with category, owner, SLA and escalation context.','queue',['Open','SLA risk','Escalated','Resolved'],['38','7','3','214'],['Ticket','Category','Owner','Priority','State'],[['TKT-8821','EMI','Support L1','High','Open'],['TKT-8818','Policy','Support L2','Normal','Escalated']],['Open ticket','Assign','Escalate'],'Support workflows retain case ownership and SLA state.'),
  'dashboard':c('Portal Dashboard','Role-specific operational overview with direct links into active work queues.','dashboard',['Active work','Pending decisions','Due today','Attention'],['42','12','18','7'],['Area','Value','State'],[['Policy operations','42 items','Healthy'],['Financial operations','12 decisions','Review'],['Customer operations','18 due','Attention']],['Open work queue','View alerts','Refresh'],'Dashboard is an entry point; each operational module remains a separate workspace.'),
};

export function getScreenCatalog(slug:string){return screenCatalog[slug]||c(
  slug.replaceAll('-',' ').replace(/\b\w/g,x=>x.toUpperCase()),
  'Dedicated DISH workspace for this module, with its own records, status context and operational actions.',
  'table',
  ['Open items','Pending','Today','Exceptions'],['24','7','12','2'],
  ['Reference','Owner','State','Updated'],
  [['DISH-1001','Operations','Pending','Today'],['DISH-1002','Operations','Ready','Today'],['DISH-1003','Review desk','Exception','Yesterday']],
  ['Open record','Take action','View audit'],
  'This module has its own operational context; actions are routed through the screen-specific workflow layer.'
);}
