'use client';
import {ReactNode,useState} from 'react';
import {ArrowDownRight,ArrowUpRight,BadgeCheck,Banknote,BarChart3,Building2,CalendarDays,CheckCircle2,ChevronRight,Clock3,Copy,Download,FileCheck2,FileText,Flag,GitBranch,History,Landmark,Layers3,Link2,ListChecks,MapPin,MessageSquare,MoreHorizontal,PackageCheck,Percent,Play,Plus,RefreshCcw,Search,Send,Settings2,ShieldAlert,ShieldCheck,SlidersHorizontal,Timer,TriangleAlert,UserCheck,UserRound,Users,WalletCards,XCircle} from 'lucide-react';
import {getScreenCatalog} from './ScreenSpecificCatalog';

type Props={role:string;slug:string};
type Ctx={key:string;title:string;sub:string;d:ReturnType<typeof getScreenCatalog>};
const A={kpi:(d:any)=>d.kpis.slice(0,4).map((k:string,i:number)=><div className="metric card" key={k}><span>{k}</span><strong>{d.values[i]||'—'}</strong><small>{i===0?'Current':i===1?'Attention':i===2?'Today':'Operational'}</small></div>),button:(label:string,icon:ReactNode=null)=> <button className="btn" data-workflow-action={label}>{icon}{label}</button>,status:(x:string)=> <span className="statusPill">{x}</span>};
function head(c:Ctx,eyebrow:string){return <div className="moduleHero"><div><div className="eyebrow">{c.role.toUpperCase()} · {eyebrow}</div><h1>{c.title}</h1><p>{c.sub}</p></div><div className="heroActions">{A.button('Refresh',<RefreshCcw size={15}/>)}{A.button(c.d.actions[0]||'Open',<ArrowUpRight size={15}/>)}</div></div>}
function useCtx(role:string,slug:string):Ctx{const aliases:any={opsadmin:{approvals:'alerts-approvals',policies:'policy-book',lifecycle:'lifecycle-manager',users:'user-master',kyc:'kyc-approval-queue',nominees:'nominee-management',cities:'city-master',developers:'developer-master',assets:'property-asset-master',allocations:'asset-allocation',ledger:'central-ledger',yield:'yield-engine',payouts:'payout-queue',settlements:'refund-settlement',documents:'document-center',support:'ticket-queue'},supportadmin:{support:'ticket-queue',sla:'sla-monitor',users:'user-master',policies:'policy-book',documents:'document-center'},kycadmin:{kyc:'kyc-approval-queue','kyc-users':'user-kyc-master',policies:'policy-book',proposals:'proposal-queue',nominees:'nominee-management',audit:'audit-logs'},agent:{performance:'performance-analytics',clients:'client-registry',policies:'policy-book',emi:'emi-follow-up','payment-links':'payment-links','missed-emis':'missed-emi-alerts','follow-ups':'follow-up-tasks','lapse-warnings':'lapse-warnings',commission:'commission','tds':'tds-statements',payouts:'payout-statements'}};const key=aliases[role]?.[slug]||slug,d=getScreenCatalog(key);return {role,slug,key,title:d.title,sub:d.sub,d}}

function Dashboard({c}:{c:Ctx}){return <><div className="dashboardIntro card"><div className="eyebrow">COMMAND SNAPSHOT</div><div className="dashboardSplit"><div><h2>{c.title}</h2><p>{c.sub}</p></div><div className="liveBadge"><span/>Live workspace</div></div></div><div className="metricGrid">{A.kpi(c.d)}</div><div className="contentGrid"><section className="card"><div className="sectionHead"><div><span className="eyebrow">PRIORITIES</span><h3>What needs attention</h3></div><Flag size={18}/></div>{c.d.rows.map((r,i)=><div className="priorityRow" key={i}><div><strong>{r[0]}</strong><small>{r.slice(1,-1).join(' · ')}</small></div>{A.status(r[r.length-1])}<ChevronRight size={15}/></div>)}</section><aside className="card"><span className="eyebrow">QUICK ACTIONS</span><h3>Move into work</h3><div className="stack">{c.d.actions.map(a=>A.button(a,<Play size={14}/>))}</div></aside></div></>}
function Table({c}:{c:Ctx}){const [q,setQ]=useState('');const rows=c.d.rows.filter(r=>r.join(' ').toLowerCase().includes(q.toLowerCase()));return <><div className="metricGrid">{A.kpi(c.d)}</div><div className="card dataWorkspace"><div className="dataHeader"><div><span className="eyebrow">RECORD WORKSPACE</span><h3>{c.title}</h3></div><div className="searchBox"><Search size={15}/><input placeholder="Search records" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="chipRow"><button className="btn"><SlidersHorizontal size={14}/> Saved view</button><button className="btn"><CalendarDays size={14}/> Today</button>{A.button('Export',<Download size={14}/>)}</div><div className="tableWrap"><table><thead><tr>{c.d.columns.map(x=><th key={x}>{x}</th>)}<th/></tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{j===r.length-1?A.status(x):x}</td>)}<td><button className="tableAction" data-workflow-action={c.d.actions[i%c.d.actions.length]||'Open'}>{c.d.actions[i%c.d.actions.length]||'Open'}<ChevronRight size={13}/></button></td></tr>)}</tbody></table></div></div></>}
function Queue({c}:{c:Ctx}){return <><div className="metricGrid">{A.kpi(c.d)}</div><div className="queueBoard"><div className="queueColumn"><div className="queueTitle"><Timer size={16}/> Incoming</div>{c.d.rows.map((r,i)=><div className="queueCard card" key={i}><div className="queueCardTop"><strong>{r[0]}</strong>{A.status(r[r.length-1])}</div><p>{r.slice(1,-1).join(' · ')}</p><div className="queueMeta"><Clock3 size={13}/> {i+2}h old <span/> <Users size={13}/> {i+1} reviewer</div><button className="linkAction" data-workflow-action={c.d.actions[i%c.d.actions.length]}>Review case <ChevronRight size={13}/></button></div>)}</div><aside className="card queueInsights"><span className="eyebrow">DECISION FLOW</span><h3>Queue pressure</h3><div className="pressure"><div><strong>72%</strong><span>within SLA</span></div><div><strong>{c.d.values[1]||'—'}</strong><span>needs review</span></div></div>{c.d.actions.map(a=>A.button(a,<CheckCircle2 size={14}/>))}</aside></div></>}
function Detail({c}:{c:Ctx}){return <><div className="detailBanner card"><div className="identity"><div className="identityIcon"><UserRound size={21}/></div><div><span className="eyebrow">PRIMARY RECORD</span><h2>{c.d.rows[0]?.[0]||c.title}</h2><p>{c.sub}</p></div></div><div className="detailState">{A.status(c.d.rows[0]?.[c.d.rows[0].length-1]||'Active')}<small>Last reviewed today</small></div></div><div className="detailGrid"><section className="card"><div className="sectionHead"><h3>Record profile</h3><MoreHorizontal size={17}/></div>{c.d.columns.map((col,i)=><div className="profileRow" key={col}><span>{col}</span><strong>{c.d.rows[0]?.[i]||'—'}</strong></div>)}</section><section className="card"><div className="sectionHead"><h3>Relationship map</h3><GitBranch size={17}/></div><div className="relationship"><div><BadgeCheck size={16}/> Primary</div><span/><div><Users size={16}/> Owner</div><span/><div><Building2 size={16}/> Asset</div></div>{c.d.actions.map(a=>A.button(a,<Link2 size={14}/>))}</section></div></>}
function Form({c}:{c:Ctx}){return <><div className="formProgress"><div className="active"><span>01</span> Details</div><div><span>02</span> Validate</div><div><span>03</span> Review</div><div><span>04</span> Submit</div></div><div className="formGrid"><section className="card formPanel"><div className="eyebrow">ENTRY WORKBENCH</div><h3>Configure {c.title}</h3>{c.d.columns.slice(0,4).map((x,i)=><label key={x}>{x}<input defaultValue={c.d.rows[0]?.[i]||''} placeholder={`Enter ${x.toLowerCase()}`}/></label>)}<label>Operational note<textarea placeholder="Record context, evidence or rationale…"/></label><div className="formActions">{c.d.actions.map(a=>A.button(a,<CheckCircle2 size={14}/>))}</div></section><aside className="card validationPanel"><ShieldCheck size={21}/><h3>Validation guardrails</h3>{['Required fields','Role permission','Duplicate check','Audit capture'].map(x=><div key={x}><CheckCircle2 size={14}/>{x}</div>)}</aside></div></>}
function Chart({c}:{c:Ctx}){return <><div className="metricGrid">{A.kpi(c.d)}</div><div className="card chartCanvas"><div className="sectionHead"><div><span className="eyebrow">TREND & PROJECTION</span><h3>{c.title}</h3></div><BarChart3 size={19}/></div><div className="chartBars">{c.d.values.map((v,i)=><div className="chartBar" key={i}><span>{v}</span><i style={{height:`${30+(i*17)%62}%`}}/><small>{c.d.kpis[i]||`Period ${i+1}`}</small></div>)}</div></div><div className="insightStrip card"><Percent size={18}/><div><strong>Operational interpretation</strong><span>{c.d.note}</span></div></div></>}
function Timeline({c}:{c:Ctx}){return <><div className="timelineHeader card"><div><span className="eyebrow">EVENT STREAM</span><h2>{c.title}</h2></div><History size={19}/></div><div className="timelineList">{c.d.rows.map((r,i)=><div className="eventRow" key={i}><div className="eventDot"/><div className="eventMain"><strong>{r[0]}</strong><span>{r.slice(1,-1).join(' · ')}</span></div><time>{r[r.length-1]}</time><button className="tableAction" data-workflow-action={c.d.actions[i%c.d.actions.length]}>Inspect <ChevronRight size={13}/></button></div>)}</div><div className="card auditFooter"><ShieldCheck size={16}/><span>{c.d.note}</span></div></>}
function Settings({c}:{c:Ctx}){return <><div className="settingsSummary card"><div><span className="eyebrow">CONTROL PLANE</span><h2>{c.title}</h2><p>{c.sub}</p></div><ShieldAlert size={22}/></div><div className="settingsGrid">{c.d.rows.map((r,i)=><div className="card settingCard" key={i}><div className="settingIcon"><Settings2 size={17}/></div><div><span>{r[0]}</span><strong>{r[r.length-2]||'—'}</strong><small>{r.slice(1,-2).join(' · ')}</small></div>{A.status(r[r.length-1])}<button className="iconBtn" data-workflow-action={c.d.actions[i%c.d.actions.length]}><ChevronRight size={15}/></button></div>)}</div></>}
function Unique(c:Ctx){const n=c.key.length%10;const body=[<Dashboard c={c}/>,<Table c={c}/>,<Queue c={c}/>,<Detail c={c}/>,<Form c={c}/>,<Chart c={c}/>,<Timeline c={c}/>,<Settings c={c}/>,<Queue c={c}/>,<Detail c={c}/>][n];return <div className="screenWorkspace">{head(c, c.d.view.toUpperCase())}{body}</div>}

export default function ScreenWorkspace({role,slug}:Props){const c=useCtx(role,slug);return <Unique {...c}/>}
