'use client';
import {useState} from 'react';
import {Download,CheckCircle2,CreditCard,FileText,Headphones,ShieldCheck,Landmark,TrendingUp,UserRound,AlertTriangle} from 'lucide-react';

type Row=string[];
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
function Shell({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <div className="moduleScreen"><div className="moduleHero"><div><div className="eyebrow">POLICYHOLDER · SELF-SERVICE</div><h1>{title}</h1><p className="subtitle">{sub}</p></div></div>{children}</div>}
function Cards({items}:{items:[string,string,string?][]}){return <div className="metricGrid">{items.map(([a,b,c])=><div className="card metric" key={a}><div className="metricLabel">{a}</div><div className="metricValue">{b}</div>{c&&<div className="delta">{c}</div>}</div>)}</div>}
function Table({headers,rows}:{headers:string[];rows:Row[]}){return <section className="section"><div className="tableWrap"><div className="record tableHeader"><span className="recordMain"><strong>{headers.join('  ·  ')}</strong></span></div>{rows.map((r,i)=><div className="record" key={i}><span className="recordMain"><strong>{r[0]}</strong><span>{r.slice(1,-1).join(' · ')}</span></span><span className="status">{r[r.length-1]}</span></div>)}</div></section>}
function Action({children,onClick}:{children:React.ReactNode;onClick?:()=>void}){return <button className="btn primary" onClick={onClick}>{children}</button>}
const payments=[['05 Aug 2026','₹10,000','RZP-882104','Paid'],['05 Jul 2026','₹10,000','RZP-871942','Paid'],['05 Jun 2026','₹10,000','RZP-860331','Paid'],['05 May 2026','₹10,000','RZP-849882','Paid']];
export default function UserPortalScreen({slug}:{slug:string}){const [notice,setNotice]=useState('');const [autopay,setAutopay]=useState(true);const done=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(''),1800)};
if(slug==='dashboard')return <Shell title="My Dashboard" sub="Policy status, EMI progress and benefit timeline at a glance."><Cards items={[["Monthly EMI","₹10,000","EMI running"],["Total Invested","₹1,80,000","18 successful EMIs"],["EMI Progress","18 / 36","50% complete"],["Yield Starts","Month 37","after final EMI"]]}/><section className="section"><div className="sectionHead"><div><div className="eyebrow">POLICY</div><h2>IREC-2024-00841</h2></div><span className="status">EMI RUNNING</span></div><div className="card largeCard"><h3>Policy journey</h3><p className="muted">Proposal → Active → EMI Running → EMI Completed → Benefit Active → Matured / Closed</p><div className="progress"><span style={{width:'50%'}}/></div><p>Next auto-debit: 05 Sep 2026 · ₹10,000</p></div></section></Shell>;
if(slug==='my-policy')return <Shell title="My Policy" sub="Policy identity, lifecycle, lock-in information and servicing details."><Cards items={[["Policy No.","IREC-2024-00841","Active"],["Issue Date","05 Mar 2025"],["Tenure","36 months"],["Agent","AG-2041","Rajesh Kumar"]]}/><div className="dashboardGrid"><div className="card largeCard"><h2>Policy details</h2><p>Monthly EMI <strong>₹10,000</strong></p><p>Total corpus <strong>₹3,60,000</strong></p><p>Current state <strong>EMI RUNNING</strong></p><p>Cooling-off <strong>Completed</strong></p></div><div className="card largeCard"><h2>Lifecycle</h2><p className="muted">18 of 36 EMIs completed. Yield disbursement begins one month after the last successful EMI.</p><div className="progress"><span style={{width:'50%'}}/></div></div></div></Shell>;
if(slug==='payments-emi')return <Shell title="Payments & EMI" sub="Manage monthly EMI, auto-pay, failed-payment recovery and receipts."><Cards items={[["Monthly EMI","₹10,000"],["Next Debit","05 Sep 2026"],["Paid EMIs","18 / 36"],["Auto-pay",autopay?'Active':'Paused'] ]}/><section className="section"><div className="sectionHead"><div><div className="eyebrow">AUTO-PAY</div><h2>NACH mandate</h2></div><Action onClick={()=>{setAutopay(!autopay);done(autopay?'Auto-pay paused':'Auto-pay resumed')}}>{autopay?'Pause auto-pay':'Resume auto-pay'}</Action></div><p className="muted">Bank ending 4821 · mandate active · monthly debit on the 5th.</p></section><Table headers={['Date','Amount','Bank reference','Status']} rows={payments}/></Shell>;
if(slug==='yield-benefits')return <Shell title="Yield & Benefits" sub="Monthly benefit statements, payout preference and long-term benefit projection."><Cards items={[["Benefit Status","Starts Month 37"],["Projected Year 1","₹43,200","12% of corpus / year"],["Corpus","₹3,60,000"],["Preference","Bank payout"]]}/><div className="dashboardGrid"><div className="card largeCard"><TrendingUp/><h2>Benefit projection</h2><p className="muted">Expected yield growth milestones: 10 years · 20 years · 40 years. Monthly yield begins after EMI completion.</p><div className="progress"><span style={{width:'62%'}}/></div></div><div className="card largeCard"><Landmark/><h2>Yield preference</h2><p>Current choice: <strong>Monthly bank payout</strong></p><Action onClick={()=>done('Preference change request submitted')}>Request preference change</Action></div></div></Shell>;
if(slug==='payout-tracking')return <Shell title="Payout Tracking" sub="Track benefit credits from payout reference through bank confirmation."><Cards items={[["Total Received","₹0","Benefits not started"],["Next Payout","Month 37"],["Bank","•••• 4821"],["Status","Scheduled"]]}/><Table headers={['Payout','Amount','Bank reference','Credit status']} rows={[["Month 37","₹3,600","Pending allocation","Scheduled"],["Month 38","₹3,600","—","Projected"],["Month 39","₹3,600","—","Projected"]]}/></Shell>;
if(slug==='document-center')return <Shell title="Document Center" sub="Policy bond, correspondence and generated policy documents in one archive."><Cards items={[["Documents","7"],["Policy Bond","Available"],["Courier","Delivered"],["AWB","DLV-483921"]]}/><Table headers={['Document','Available','Format','Status']} rows={[["Policy Bond","After activation","PDF + courier","Available"],["EMI Schedule","After activation","PDF","Available"],["KYC Pack","After approval","PDF","Available"],["Communication Letter","As issued","PDF archive","Available"]]}/><Action onClick={()=>done('Policy Bond download prepared')}><Download size={15}/> Download Policy Bond</Action></Shell>;
if(slug==='emi-receipts')return <Shell title="EMI Receipts" sub="Download a payment receipt for every successful monthly EMI."><Cards items={[["Receipts","18"],["Latest","05 Aug 2026"],["Latest EMI","₹10,000"],["Status","Paid"]]}/><Table headers={['Payment date','Amount','Reference','Receipt']} rows={payments.map(x=>[x[0],x[1],x[2],'Download'])}/><Action onClick={()=>done('Latest receipt prepared')}><Download size={15}/> Download latest receipt</Action></Shell>;
if(slug==='annual-statements')return <Shell title="Annual Statements" sub="Year-wise investment and benefit statements for your policy."><Cards items={[["FY 2025-26","Available"],["Invested","₹1,20,000"],["Benefits","₹0"],["Format","PDF"]]}/><Table headers={['Financial year','Invested','Benefits received','Document']} rows={[["2025–26","₹1,20,000","₹0","Available"],["2026–27","₹60,000 YTD","₹0","In progress"]]}/><Action onClick={()=>done('Annual statement prepared')}><Download size={15}/> Download FY 2025–26</Action></Shell>;
if(slug==='tax-income-summary')return <Shell title="Tax / Income Summary" sub="Annual benefit summary for income declaration and ITR purposes."><Cards items={[["FY 2025-26 Income","₹0"],["Yield Received","₹0"],["Statement","Available"],["Purpose","ITR"]]}/><div className="card largeCard"><FileText/><h2>Tax summary</h2><p>No yield income was credited during FY 2025–26 because the policy is still in the EMI-running stage.</p><Action onClick={()=>done('Tax summary PDF prepared')}><Download size={15}/> Download PDF</Action></div></Shell>;
if(['nominee-update','bank-change','address-update','termination-request'].includes(slug)){const cfg:any={'nominee-update':['Nominee Update','Update nominee details attached to your policy.','Current nominee: Priya Mehta · Relationship: Spouse'], 'bank-change':['Bank Change','Request a change to the verified bank account used for payouts.','Current payout bank: HDFC Bank · •••• 4821'], 'address-update':['Address Update','Submit a servicing request to update your registered address.','Current city: Mumbai · Aadhaar/address proof verification required'], 'termination-request':['Termination Request','Request policy termination and review the settlement process.','Refund is calculated from EMIs paid less applicable deductions; cooling-off rules apply.']};const [t,s,context]=cfg[slug];return <Shell title={t} sub={s}><div className="card largeCard"><h2>Current record</h2><p>{context}</p>{slug==='termination-request'&&<p className="muted"><AlertTriangle size={15}/> Termination may trigger settlement calculation and applicable commission clawback.</p>}</div><section className="section"><h2>Submit request</h2><div className="detailGrid"><label>Policy<input value="IREC-2024-00841" readOnly/></label><label>Request details<input placeholder={`Enter ${t.toLowerCase()} details`}/></label><label>Supporting reference<input placeholder="Document / reason / reference"/></label></div><Action onClick={()=>done(`${t} submitted for verification`)}><CheckCircle2 size={15}/> Submit request</Action></section></Shell>}
if(slug==='support-grievance')return <Shell title="Support / Grievance" sub="Raise and track EMI, KYC, yield, general or legal service tickets."><Cards items={[["Open Tickets","1"],["SLA","24 hrs","L1"],["Resolved","4"],["Escalation","Support → Ops → Super"]]}/><Table headers={['Ticket','Category','Updated','Status']} rows={[["TKT-24081","Payment / EMI","Today 10:42","Open"],["TKT-23812","Document","12 Aug 2026","Resolved"]]}/><Action onClick={()=>done('New support ticket created')}><Headphones size={15}/> Raise ticket</Action></Shell>;
if(slug==='profile-security')return <Shell title="Profile & Security" sub="Personal details, verified contacts, password and active-session security."><div className="dashboardGrid"><div className="card largeCard"><UserRound/><h2>Profile</h2><p>Aarav Mehta</p><p>aarav@example.com · +91 ••••• 48210</p><p><CheckCircle2 size={15}/> Email and mobile verified</p></div><div className="card largeCard"><ShieldCheck/><h2>Security</h2><p>Password last changed 32 days ago</p><p>2 active sessions</p><Action onClick={()=>done('Other sessions signed out')}>Sign out other sessions</Action></div></div></Shell>;
return <Shell title="User Portal" sub="This route is not part of the documented policyholder menu."><div className="card largeCard"><CreditCard/><p>Choose a feature from the policyholder menu.</p></div></Shell>;
}
