'use client';
import {useEffect,useMemo,useState,type ReactNode} from 'react';
import {AlertTriangle,ArrowRight,CheckCircle2,Clock3,FileText,History,Info,Link2,ShieldCheck,UserCheck,X} from 'lucide-react';

type Mode='approval'|'financial'|'verification'|'document'|'support'|'security'|'request'|'settings'|'default';
type M={title:string;eyebrow:string;description:string;mode:Mode;steps:string[];fields:string[]};
type S={screen:string;action:string}|null;
const meta:Record<string,M>={
'alerts-approvals':{title:'Review approval decision',eyebrow:'ALERTS & APPROVALS',description:'Review the selected case, evidence and audit reason before recording a decision.',mode:'approval',steps:['Case context','Evidence','Decision','Audit'],fields:['Decision','Reason','Operator note']},
'proposal-queue':{title:'Approve proposal for policy creation',eyebrow:'PROPOSAL QUEUE',description:'Validate contribution, tenure, KYC readiness and allocation context.',mode:'approval',steps:['Proposal','Eligibility','Policy mapping','Decision'],fields:['Monthly EMI','Tenure','KYC state','Decision note']},
'kyc-approval-queue':{title:'Verify customer identity',eyebrow:'KYC APPROVAL QUEUE',description:'Review identity evidence and record an explicit verification outcome.',mode:'verification',steps:['Identity packet','Evidence','Decision','Audit'],fields:['PAN result','Aadhaar result','Selfie match','Reviewer note']},
'bank-verification':{title:'Verify bank account',eyebrow:'BANK VERIFICATION',description:'Confirm account-holder and bank evidence before accepting payout instructions.',mode:'verification',steps:['Account','Bank evidence','Verification','Audit'],fields:['Account holder','Account number','IFSC','Verification method']},
'nominee-management':{title:'Review nominee change',eyebrow:'NOMINEE MANAGEMENT',description:'Check nominee identity, relationship, allocation and consent evidence.',mode:'verification',steps:['Nominee','Relationship','Evidence','Consent'],fields:['Nominee name','Relationship','Share %','Consent reference']},
'address-verification':{title:'Verify address',eyebrow:'ADDRESS VERIFICATION',description:'Review the address proof and verification outcome for the selected record.',mode:'verification',steps:['Address','Proof','Validation','Audit'],fields:['Address line','City','PIN','Proof type']},
'central-ledger':{title:'Open ledger control action',eyebrow:'CENTRAL LEDGER',description:'Review the source entry and intended financial movement before proceeding.',mode:'financial',steps:['Source entry','Impact','Authorization','Audit'],fields:['Reference','Amount','Account','Operator reason']},
'emi-collection':{title:'Open EMI recovery action',eyebrow:'EMI COLLECTION',description:'Choose a recovery route for the selected failed or pending EMI.',mode:'financial',steps:['Failed attempt','Recovery route','Customer notice','Audit'],fields:['Failure reason','Retry date','Recovery route','Collection note']},
'refund-settlement':{title:'Review refund settlement',eyebrow:'REFUND & SETTLEMENT',description:'Review cooling-off status, deductions and refundable amount before settlement.',mode:'financial',steps:['Calculation','Cooling-off','Approval','Payout'],fields:['Paid amount','Deductions','Refundable amount','Approval note']},
'yield-engine':{title:'Preview yield calculation',eyebrow:'YIELD ENGINE',description:'Run a preview of the monthly benefit calculation without posting a financial mutation.',mode:'financial',steps:['Cohort','Inputs','Calculation','Preview'],fields:['Corpus','Rate','Period','Scenario']},
'payout-queue':{title:'Review payout release',eyebrow:'PAYOUT QUEUE',description:'Inspect payout eligibility and bank verification before release.',mode:'financial',steps:['Payout','Bank','Approval','Gateway'],fields:['Payout amount','Bank state','Release decision','Operator note']},
'failed-payouts':{title:'Diagnose failed payout',eyebrow:'FAILED PAYOUTS',description:'Review provider response and decide whether the payout can be retried.',mode:'financial',steps:['Failure','Diagnosis','Retry','Audit'],fields:['Failure code','Provider reference','Retry route','Resolution note']},
'document-center':{title:'Open policy document',eyebrow:'DOCUMENT CENTER',description:'Inspect document metadata and the requested delivery format.',mode:'document',steps:['Document','Version','Access','Delivery'],fields:['Document type','Policy','Version','Delivery format']},
'emi-receipts':{title:'Download EMI receipt',eyebrow:'EMI RECEIPTS',description:'Prepare the selected payment receipt for the policyholder.',mode:'document',steps:['Payment','Receipt','Access','Download'],fields:['Receipt period','Payment reference','Policy','Format']},
'print-queue':{title:'Control print packet',eyebrow:'PRINT QUEUE',description:'Review packet contents and printer assignment before print execution.',mode:'document',steps:['Packet','Printer','Confirmation','Audit'],fields:['Packet ID','Printer','Document count','Operator note']},
'courier':{title:'Dispatch document packet',eyebrow:'COURIER / AWB',description:'Prepare the physical document packet for courier assignment.',mode:'document',steps:['Packet','Address','Courier','Dispatch'],fields:['Packet ID','Destination','Courier','AWB']},
'ticket-queue':{title:'Work support ticket',eyebrow:'TICKET QUEUE',description:'Review customer context, ownership and next resolution action.',mode:'support',steps:['Customer','Issue','Owner','Resolution'],fields:['Category','Owner','Priority','Resolution note']},
'sla-monitor':{title:'Resolve SLA risk',eyebrow:'SLA MONITOR',description:'Review the response clock and choose the correct operational escalation.',mode:'support',steps:['Clock','Owner','Escalation','Audit'],fields:['Target','Current age','Owner','Escalation reason']},
escalations:{title:'Process escalation',eyebrow:'ESCALATIONS',description:'Move the case through the defined Support → Ops → Super Admin path.',mode:'support',steps:['Case','Current level','Next owner','Audit'],fields:['Current owner','Escalation level','Reason','Operator note']},
'audit-logs':{title:'Inspect audit event',eyebrow:'AUDIT LOGS',description:'Inspect the actor, sensitive action and recorded audit metadata.',mode:'security',steps:['Event','Actor','Action','Evidence'],fields:['Actor','Module','Action','Reference']},
'security-events':{title:'Investigate security event',eyebrow:'SECURITY EVENTS',description:'Review the authentication or access anomaly and record the investigation route.',mode:'security',steps:['Event','Risk','Investigation','Disposition'],fields:['Event type','Risk level','Device / location','Disposition']},
'roles-permissions':{title:'Edit RBAC permissions',eyebrow:'ROLES & PERMISSIONS',description:'Review role scope and sensitive permissions before applying a controlled change.',mode:'security',steps:['Role','Scope','Permissions','Audit'],fields:['Role','Permission set','Sensitive actions','Change reason']},
'admin-accounts':{title:'Change administrator access',eyebrow:'ADMIN ACCOUNTS',description:'Review the administrator identity before changing access state.',mode:'security',steps:['Identity','Access','Confirmation','Audit'],fields:['Admin ID','Role','Access state','Reason']},
'profile-security':{title:'Manage profile security',eyebrow:'PROFILE & SECURITY',description:'Review account security state and selected session or notification setting.',mode:'security',steps:['Account','Setting','Confirmation','Audit'],fields:['Setting','Current state','New state','Confirmation note']},
'nominee-update':{title:'Submit nominee update',eyebrow:'NOMINEE UPDATE',description:'Capture nominee identity and relationship evidence for policyholder review.',mode:'request',steps:['Nominee','Evidence','Review','Submit'],fields:['Nominee name','Relationship','Share %','Evidence']},
'bank-change':{title:'Submit bank change',eyebrow:'BANK CHANGE REQUEST',description:'Capture the new account details and verification route.',mode:'request',steps:['Account','Verification','Consent','Submit'],fields:['Account holder','Account number','IFSC','Verification route']},
'address-update':{title:'Submit address update',eyebrow:'ADDRESS CHANGE REQUEST',description:'Capture the new address and supporting proof.',mode:'request',steps:['Address','Proof','Review','Submit'],fields:['Address','City','PIN','Proof']},
'termination-request':{title:'Review termination request',eyebrow:'TERMINATION REQUEST',description:'Review reason, cooling-off position and settlement context before submission.',mode:'request',steps:['Reason','Cooling-off','Settlement','Submit'],fields:['Reason','Cooling-off state','Settlement view','Customer note']},
'system-settings':{title:'Change system setting',eyebrow:'SYSTEM SETTINGS',description:'Review the sensitive configuration change and its operational impact.',mode:'settings',steps:['Current','Change','Risk','Audit'],fields:['Setting','Current value','New value','Change reason']},
'integrations':{title:'Test provider connection',eyebrow:'INTEGRATIONS',description:'Inspect provider health and test the selected integration.',mode:'settings',steps:['Provider','Connectivity','Response','Audit'],fields:['Provider','Purpose','Environment','Test note']},
'feature-flags':{title:'Change feature rollout',eyebrow:'FEATURE FLAGS',description:'Review role scope and rollout percentage before changing a feature state.',mode:'settings',steps:['Flag','Scope','Rollout','Audit'],fields:['Feature','Audience','Rollout %','Change reason']}
};
const aliases:any={superadmin:'admin',opsadmin:'opsadmin',supportadmin:'supportadmin',kycadmin:'kycadmin',agent:'agent',user:'user',admin:'admin'};
function path(){if(typeof window==='undefined')return {role:'admin',slug:'dashboard'};const p=window.location.pathname.split('/').filter(Boolean);return {role:p[0]||'admin',slug:p[1]||'dashboard'};}
function baseMeta(screen:string,action:string):M{return {title:`${action} · ${screen.replaceAll('-',' ')}`,eyebrow:'SCREEN-SPECIFIC WORKFLOW',description:`Review the ${screen.replaceAll('-',' ')} context and continue the selected workflow.`,mode:/kyc|bank|address|nominee|verification/.test(screen)?'verification':/payment|payout|emi|yield|ledger|settlement|commission|tds/.test(screen)?'financial':/document|print|courier|delivery|receipt|statement|tax/.test(screen)?'document':/support|sla|escalation|ticket/.test(screen)?'support':/security|audit|role|session|admin/.test(screen)?'security':/request|termination/.test(screen)?'request':/settings|integration|feature/.test(screen)?'settings':'default',steps:['Context','Review','Action','Audit'],fields:['Selected record','Current state','Operator input','Reason']};}
function normalize(m:M,action:string):M{return {...m,title:`${m.title.replace(/^.*?· /,'')} · ${action}`,description:`${m.description} Selected action: ${action}.`};}
function Modal(){const[state,setState]=useState<S>(null);const[catalog,setCatalog]=useState<string>('');const loc=path();useEffect(()=>{const click=(e:MouseEvent)=>{const el=(e.target as HTMLElement)?.closest?.('[data-workflow-action]') as HTMLElement|null;if(!el)return;if(el.closest('a'))return;const action=el.getAttribute('data-workflow-action');if(!action)return;e.preventDefault();e.stopPropagation();setState({screen:aliases[loc.role]?`${loc.role}:${loc.slug}`:loc.slug,action});};document.addEventListener('click',click,true);return()=>document.removeEventListener('click',click,true)},[loc.role,loc.slug]);useEffect(()=>{if(!state)return;setCatalog(state.screen)},[state]);const screenKey=state?.screen.split(':').pop()||'dashboard';const m=useMemo(()=>{const raw=meta[screenKey]||meta[state?.screen||'']||baseMeta(screenKey,state?.action||'Open');return state?normalize(raw,state.action):raw},[screenKey,state]);if(!state)return null;return <div className="workflowModalBackdrop" role="dialog" aria-modal="true" onMouseDown={e=>{if(e.currentTarget===e.target)setState(null)}}><div className={`workflowModal workflow-${m.mode}`}><button className="workflowClose" onClick={()=>setState(null)} aria-label="Close"><X size={17}/></button><div className="workflowTop"><div className="workflowIcon">{m.mode==='verification'?<UserCheck size={19}/>:m.mode==='financial'?<ShieldCheck size={19}/>:m.mode==='document'?<FileText size={19}/>:m.mode==='support'?<MessageSquareIcon/>:m.mode==='security'?<ShieldCheck size={19}/>:<Info size={19}/>}</div><div><span className="eyebrow">{m.eyebrow}</span><h2>{m.title}</h2><p>{m.description}</p></div></div><div className="workflowSteps">{m.steps.map((s,i)=><div className={i===0?'active':''} key={s}><span>{i+1}</span><small>{s}</small></div>)}</div><div className="workflowBody"><section className="workflowFacts"><span className="eyebrow">WORKFLOW CONTEXT</span>{m.fields.map((f,i)=><label key={f}>{f}{i===m.fields.length-1?<textarea placeholder={`Add ${f.toLowerCase()}…`}/>:<input defaultValue={i===0?state.action:''} placeholder={`Enter ${f.toLowerCase()}`}/>}</label>)}</section><aside className="workflowAside"><div className="workflowState"><Clock3 size={15}/><div><strong>Demo workflow</strong><span>No production transaction is executed.</span></div></div><div className="workflowState"><History size={15}/><div><strong>Audit context</strong><span>Role: {loc.role} · Screen: {screenKey}</span></div></div></aside></div><div className="workflowFooter"><button className="btn" onClick={()=>setState(null)}>Cancel</button><button className="btn primary" onClick={()=>setState(null)}><CheckCircle2 size={15}/> Continue</button></div></div></div>}
function MessageSquareIcon(){return <MessageSquare size={19}/>}
export default Modal;
