'use client';

import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,ChevronRight,Clock3,Download,History,Info,ShieldCheck,X} from 'lucide-react';

type Tone='normal'|'warning'|'danger';
type Field={label:string;value?:string;placeholder?:string;type?:'text'|'select'|'textarea';options?:string[]};
type Profile={area:string;eyebrow:string;description:string;tone:Tone;facts:[string,string][];fields:Field[];steps:string[];primary:string;secondary?:string;notice?:string};
type ModalState={role:string;screen:string;action:string}|null;

const roleAliases:Record<string,Record<string,string>>={
 admin:{operations:'live-operations',approvals:'alerts-approvals',users:'user-master',roles:'roles-permissions',admins:'admin-accounts',sessions:'sessions-devices',cities:'city-master',developers:'developer-master',assets:'property-asset-master',allocations:'asset-allocation','policy-engine':'policy-creation-engine',proposals:'proposal-queue',policies:'policy-book',lifecycle:'lifecycle-manager',rules:'rules-engine',kyc:'kyc-approval-queue','kyc-users':'user-kyc-master',nominees:'nominee-management','address-verification':'address-verification',ownership:'ownership-transfer',ledger:'central-ledger','emi-collection':'emi-collection',reconciliation:'reconciliation',adjustments:'adjustments-reversals',settlements:'refund-settlement',yield:'yield-engine',payouts:'payout-queue','failed-payouts':'failed-payouts','yield-forecast':'yield-forecast',agents:'agent-master',hierarchy:'hierarchy',commission:'commission-engine','commission-holds':'commission-holds',clawbacks:'clawbacks','agent-performance':'performance-analytics',documents:'document-center','print-queue':'print-queue',courier:'courier',delivery:'delivery-tracking',reprints:'reprint-requests',support:'ticket-queue',sla:'sla-monitor',escalations:'escalations','resolution-history':'resolution-history',reports:'mis-reports',audit:'audit-logs','security-events':'security-events',webhooks:'webhook-events',jobs:'job-queues',notifications:'notifications',integrations:'integrations','feature-flags':'feature-flags','system-settings':'system-settings'},
 opsadmin:{approvals:'approvals',policies:'policies',lifecycle:'lifecycle','emi-collection':'emi-collection',reconciliation:'reconciliation',users:'users',kyc:'kyc-queue','bank-verification':'bank-verification',nominees:'nominee','address-verification':'address-verification',cities:'cities',developers:'developers',assets:'assets',allocations:'allocations',ledger:'ledger',yield:'yield',payouts:'payouts',settlements:'settlements',documents:'documents','print-queue':'print-queue',courier:'courier',support:'support',reports:'reports'},
 supportadmin:{support:'ticket-queue',sla:'sla-monitor',escalations:'escalations','resolution-history':'resolution-history',users:'users',policies:'policies',payments:'payments',documents:'documents',notifications:'notifications',broadcasts:'broadcasts',templates:'templates'},
 kycadmin:{kyc:'approval-queue','kyc-users':'user-master','bank-verification':'bank-verification','address-verification':'address-verification',nominees:'nominee-management',policies:'policies',proposals:'proposals',exceptions:'exceptions',audit:'verification-audit',reports:'reports'},
 agent:{performance:'my-performance',notices:'ho-notices',clients:'client-registry',proposal:'new-proposal','proposal-queue':'proposal-queue',policies:'policies',emi:'emi-follow-up','payment-links':'payment-links','missed-emis':'missed-emi-alerts','follow-ups':'follow-up-tasks','lapse-warnings':'lapse-warnings',commission:'commission',tds:'tds-statements',payouts:'payout-statements',support:'support',profile:'profile'},
 user:{policy:'my-policy',payments:'payments-emi',yield:'yield-benefits','payout-tracking':'payout-tracking',documents:'document-center',receipts:'emi-receipts',statements:'annual-statements','tax-summary':'tax-income-summary','nominee-request':'nominee-update','bank-request':'bank-change','address-request':'address-update',termination:'termination-request',support:'support-grievance',profile:'profile-security'}
};

const title=(s:string)=>s.split('-').map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(' ');
const screenFor=()=>{if(typeof window==='undefined')return {role:'admin',screen:'dashboard'};const p=window.location.pathname.split('/').filter(Boolean);const role=p[0]||'admin';const raw=p[1]||'dashboard';return {role,screen:roleAliases[role]?.[raw]||raw};};
const groupFor=(s:string)=>{
 if(/kyc|bank|address|nominee|verification|identity/i.test(s))return 'KYC & User Management';
 if(/emi|payment|reconcil|ledger|refund|settlement|adjustment|payout|yield|commission|tds/i.test(s))return 'Financial Operations';
 if(/proposal|policy|lifecycle|rule|asset|allocation|developer|city/i.test(s))return 'Policy & Master Data';
 if(/support|sla|escalation|resolution|ticket/i.test(s))return 'Support & Grievance';
 if(/document|print|courier|delivery|reprint/i.test(s))return 'Documents & Dispatch';
 if(/report|analytics|performance|audit|security|webhook|job|notification|integration|settings/i.test(s))return 'Control & Reporting';
 return 'Workspace Operations';
};

const actionMap:Record<string,Partial<Profile>>={
 approve:{eyebrow:'DECISION WORKBENCH',tone:'warning',steps:['Review case','Validate evidence','Decision','Audit'],primary:'Approve'},
 reject:{eyebrow:'CONTROLLED REJECTION',tone:'danger',steps:['Review case','Reason','Decision','Audit'],primary:'Reject'},
 'request correction':{eyebrow:'CORRECTION REQUEST',tone:'warning',steps:['Review evidence','Reason','Customer notice','Audit'],primary:'Request correction'},
 'request clarification':{eyebrow:'CLARIFICATION REQUEST',tone:'warning',steps:['Review proposal','Questions','Agent notice','Audit'],primary:'Request clarification'},
 verify:{eyebrow:'VERIFICATION DESK',steps:['Record','Verify','Decision','Audit'],primary:'Verify'},
 'verify bank':{eyebrow:'PAYOUT ELIGIBILITY',steps:['Account','Verification','Decision','Audit'],primary:'Verify bank'},
 retry:{eyebrow:'RECOVERY ACTION',tone:'warning',steps:['Failure','Recovery','Retry','Audit'],primary:'Retry'},
 'retry mandate':{eyebrow:'EMI RECOVERY',tone:'warning',steps:['Failure','Recovery','Customer notice','Audit'],primary:'Retry mandate',secondary:'Send payment link'},
 'retry payout':{eyebrow:'PAYOUT RECOVERY',tone:'danger',steps:['Failure','Diagnosis','Retry','Audit'],primary:'Retry payout',secondary:'Escalate'},
 'send payment link':{eyebrow:'MANUAL COLLECTION',steps:['Client','Amount','Delivery','Generate'],primary:'Send payment link'},
 'generate payment link':{eyebrow:'PAYMENT LINK',steps:['Client','Amount','Delivery','Generate'],primary:'Generate payment link'},
 'approve payout':{eyebrow:'BENEFIT DISBURSEMENT',tone:'warning',steps:['Payout','Bank','Approval','Gateway'],primary:'Approve payout',secondary:'Hold payout'},
 'approve settlement':{eyebrow:'FINAL SETTLEMENT',tone:'warning',steps:['Calculation','Cooling-off','Approval','Payout'],primary:'Approve settlement',secondary:'Hold settlement'},
 'approve adjustment':{eyebrow:'CONTROLLED ADJUSTMENT',tone:'danger',steps:['Original','Correction','Approval','Audit'],primary:'Approve adjustment',secondary:'Reverse entry'},
 'advance lifecycle':{eyebrow:'STATE TRANSITION',tone:'warning',steps:['Current state','Trigger','Validation','Transition'],primary:'Advance lifecycle',secondary:'Open policy'},
 'run rule test':{eyebrow:'RULE VALIDATION',steps:['Rule','Inputs','Result','Audit'],primary:'Run rule test',secondary:'Edit rule'},
 allocate:{eyebrow:'ALLOCATION DECISION',steps:['Asset','Pool','Exposure','Decision'],primary:'Allocate asset',secondary:'Hold allocation'},
 'process commission':{eyebrow:'COMMISSION LEDGER',steps:['Policy','Commission','TDS','Release'],primary:'Process commission',secondary:'Place hold'},
 escalate:{eyebrow:'ESCALATION CONTROL',tone:'warning',steps:['SLA review','Owner','Reason','Audit'],primary:'Escalate',secondary:'Keep assigned'},
 'raise ticket':{eyebrow:'SUPPORT CASE',steps:['Category','Evidence','Owner','Submit'],primary:'Raise ticket'},
 'save changes':{eyebrow:'CONTROLLED UPDATE',steps:['Review','Validate','Save','Audit'],primary:'Save changes'},
 'submit':{eyebrow:'SUBMISSION',steps:['Review','Validate','Submit','Audit'],primary:'Submit'},
 'create':{eyebrow:'CREATE RECORD',steps:['Details','Validation','Review','Create'],primary:'Create'},
 'add user':{eyebrow:'USER ONBOARDING',steps:['Identity','Role','Access','Create'],primary:'Add user'},
 'create user':{eyebrow:'USER ONBOARDING',steps:['Identity','Role','KYC','Create'],primary:'Create user'},
 'export':{eyebrow:'REPORT EXPORT',steps:['Scope','Filters','Generate','Download'],primary:'Export'},
 'download':{eyebrow:'DOCUMENT DOWNLOAD',steps:['Document','Access check','Generate','Download'],primary:'Download'},
 'print':{eyebrow:'PRINT CONTROL',steps:['Document','Printer queue','Confirmation','Audit'],primary:'Print'},
 'dispatch':{eyebrow:'DISPATCH CONTROL',steps:['Packet','Address','Courier','Dispatch'],primary:'Dispatch'},
 'pause':{eyebrow:'AUTOPAY CONTROL',tone:'warning',steps:['Mandate','Reason','Confirm','Audit'],primary:'Pause autopay'},
 resume:{eyebrow:'AUTOPAY CONTROL',steps:['Mandate','Review','Confirm','Audit'],primary:'Resume autopay'},
 'change bank':{eyebrow:'BANK CHANGE',tone:'warning',steps:['Account','Verification','OTP','Consent'],primary:'Submit bank change'},
 'update nominee':{eyebrow:'NOMINEE UPDATE',steps:['Nominee','Relationship','Evidence','Submit'],primary:'Submit nominee update'},
 'update address':{eyebrow:'ADDRESS UPDATE',steps:['Address','Proof','Review','Submit'],primary:'Submit address update'},
 terminate:{eyebrow:'TERMINATION REQUEST',tone:'danger',steps:['Reason','Cooling-off','Settlement','Submit'],primary:'Submit termination'},
 'withdraw yield':{eyebrow:'YIELD / BENEFIT CHOICE',steps:['Eligibility','Amount','Bank','Confirm'],primary:'Confirm withdrawal'},
};

const screenMap:Record<string,Partial<Profile>>={
'kyc-approval-queue':{area:'Identity decision workbench',description:'Compare the identity packet and record an explicit verification decision.',facts:[['Case','KYC-821'],['Customer','Aarav Mehta'],['Documents','PAN · Aadhaar · Selfie'],['Risk','Low']],fields:[{label:'PAN',value:'Verified',type:'select',options:['Verified','Mismatch','Unreadable']},{label:'Aadhaar',value:'Verified',type:'select',options:['Verified','Mismatch','Unreadable']},{label:'Selfie match',value:'Matched',type:'select',options:['Matched','Mismatch','Manual review']},{label:'Decision note',placeholder:'Record discrepancy or verification evidence…',type:'textarea'}]},
'bank-verification':{area:'Bank verification desk',description:'Review account holder, IFSC and verification evidence before accepting the bank record.',facts:[['Case','BNK-2201'],['Holder','Aarav Mehta'],['Bank','HDFC Bank'],['State','Pending']],fields:[{label:'Account',value:'•••• 4821'},{label:'IFSC',value:'HDFC0001234'},{label:'Method',value:'Penny drop',type:'select',options:['Penny drop','API verification','Manual verification']},{label:'Reference',placeholder:'Verification reference'},{label:'Reviewer note',placeholder:'Add verification note…',type:'textarea'}]},
'proposal-queue':{area:'Proposal approval desk',description:'Validate client choice, tenure, KYC readiness and asset mapping before policy creation.',facts:[['Proposal','PROP-8421'],['Agent','AG-2041'],['Customer','Aarav Mehta'],['Asset','AST-001']],fields:[{label:'Monthly EMI',value:'₹10,000'},{label:'Tenure',value:'36 months',type:'select',options:['24 months','36 months','48 months']},{label:'KYC readiness',value:'Ready',type:'select',options:['Ready','Pending','Exception']},{label:'Review note',placeholder:'Approval or clarification note…',type:'textarea'}]},
'new-proposal':{area:'Client proposal builder',description:'Build a client-selected EMI proposal with no pre-packaged plan tiers.',facts:[['Minimum EMI','₹5,000'],['Tenure','24–48 months'],['Frequency','Monthly'],['Plans','None']],fields:[{label:'Client',value:'Aarav Mehta'},{label:'Monthly EMI',value:'₹10,000'},{label:'Tenure',value:'36 months',type:'select',options:['24 months','36 months','48 months']},{label:'Yield preference',value:'Choose at Month 24',type:'select',options:['Continue yield','Withdrawal preference']},{label:'Proposal note',placeholder:'Client discussion note…',type:'textarea'}]},
'emi-collection':{area:'EMI recovery desk',description:'Review a failed or pending EMI and select the appropriate recovery route.',facts:[['Policy','IREC-00840'],['Holder','Diya Shah'],['EMI','₹15,000'],['Attempt','Failed']],fields:[{label:'Debit method',value:'NACH',type:'select',options:['NACH','Manual payment']},{label:'Failure reason',value:'Mandate failed',type:'select',options:['Mandate failed','Insufficient balance','Bank timeout','Unknown']},{label:'Retry date',placeholder:'Select retry date'},{label:'Customer note',placeholder:'Record follow-up outcome…',type:'textarea'}]},
'adjustments-reversals':{area:'Financial correction desk',description:'Review the original ledger reference, correction value and reason before posting a controlled adjustment.',facts:[['Reference','ADJ-882'],['Original','LED-9919'],['Amount','₹18,000'],['Risk','High value']],fields:[{label:'Adjustment type',value:'Settlement correction',type:'select',options:['Adjustment','Reversal']},{label:'Amount',value:'₹18,000'},{label:'Reason',value:'Settlement correction',type:'select',options:['Settlement correction','Duplicate','Customer correction','Other']},{label:'Approval note',placeholder:'Mandatory reason and supporting context…',type:'textarea'}]},
'refund-settlement':{area:'Termination settlement desk',description:'Review paid EMIs, cooling-off status, deductions and refundable amount before settlement release.',facts:[['Policy','IREC-00821'],['Paid EMIs','₹90,000'],['Deductions','₹0'],['Refundable','₹90,000']],fields:[{label:'Cooling-off',value:'Eligible',type:'select',options:['Eligible','Expired','Not applicable']},{label:'Deduction reason',placeholder:'Enter deduction or N/A'},{label:'Refundable amount',value:'₹90,000'},{label:'Approval note',placeholder:'Settlement approval rationale…',type:'textarea'}]},
'lifecycle-manager':{area:'Policy lifecycle desk',description:'Review current policy state, trigger and resulting lifecycle state before advancing.',facts:[['Policy','IREC-2024-00841'],['Current','EMI Running'],['Progress','18 / 36'],['Trigger','Rule-based']],fields:[{label:'Current state',value:'EMI Running',type:'select',options:['Proposal','EMI Running','EMI Completed','Benefit Active','Lapsed','Terminated']},{label:'Trigger',value:'EMI + KYC'},{label:'Target state',value:'EMI Completed',type:'select',options:['EMI Completed','Benefit Active','Lapsed','Terminated']},{label:'Transition note',placeholder:'Record lifecycle decision…',type:'textarea'}]},
'rules-engine':{area:'Rules test bench',description:'Run a frontend test against a hard policy rule and inspect the expected result.',facts:[['Minimum EMI','₹5,000'],['Tenure','24–48 months'],['Lapse trigger','3 failures'],['Enforcement','Blocking']],fields:[{label:'Rule',value:'Minimum Monthly EMI',type:'select',options:['Minimum Monthly EMI','Minimum Tenure','Maximum Tenure','3 Consecutive EMI Failures']},{label:'Sample EMI',value:'₹10,000'},{label:'Sample tenure',value:'36 months'},{label:'Expected result',value:'Pass',type:'select',options:['Pass','Fail']},{label:'Test note',placeholder:'Test-case note…',type:'textarea'}]},
'payout-queue':{area:'Benefit payout approval desk',description:'Review payout beneficiary, amount and verified bank details before gateway submission.',facts:[['Payout','PAY-8821'],['Policy','IREC-00841'],['Amount','₹3,600'],['Gateway','Razorpay']],fields:[{label:'Bank',value:'•••• 4821'},{label:'Verification',value:'Verified',type:'select',options:['Verified','Pending','Failed']},{label:'Payout amount',value:'₹3,600'},{label:'Approval note',placeholder:'Payout approval note…',type:'textarea'}]},
'failed-payouts':{area:'Payout recovery desk',description:'Inspect the gateway failure and prepare a controlled retry or escalation.',facts:[['Payout','PAY-8812'],['Attempt','2'],['Gateway','Razorpay'],['Status','Failed']],fields:[{label:'Failure reason',value:'Bank timeout',type:'select',options:['Bank timeout','Invalid account','Gateway timeout','Unknown']},{label:'Retry method',value:'Same bank account',type:'select',options:['Same bank account','Verified alternate account']},{label:'Retry date',placeholder:'Select retry date'},{label:'Recovery note',placeholder:'Gateway response / retry rationale…',type:'textarea'}]},
'ownership-transfer':{area:'Ownership transfer case',description:'Review current owner, proposed owner and legal evidence before approving a transfer.',facts:[['Case','OWN-018'],['Policy','IREC-00841'],['Reason','Legal / succession'],['Review','Legal']],fields:[{label:'Current holder',value:'Aarav Mehta'},{label:'New holder',value:'Priya Mehta'},{label:'Legal evidence',value:'Pending',type:'select',options:['Pending','Verified','Insufficient']},{label:'Case note',placeholder:'Legal review findings…',type:'textarea'}]},
'alerts-approvals':{area:'Central approval inbox',description:'Review the requested action, priority and evidence before recording the decision.',facts:[['Case','APR-8421'],['Module','Refund'],['Requester','Ops Admin'],['Priority','High']],fields:[{label:'Priority',value:'High',type:'select',options:['High','Normal','Low']},{label:'Requester note',value:'Termination settlement review'},{label:'Decision note',placeholder:'Required reviewer rationale…',type:'textarea'}]},
'asset-allocation':{area:'Asset exposure mapping',description:'Review eligible asset, policy pool and exposure before committing the allocation.',facts:[['Asset','AST-001'],['Developer','Aster Realty'],['City','Mumbai'],['Value','₹12.4Cr']],fields:[{label:'Policy pool',value:'Pool MUM-04',type:'select',options:['Pool MUM-04','Pool MUM-05','Hold']},{label:'Allocation state',value:'Ready',type:'select',options:['Ready','Hold','Review']},{label:'Allocation note',placeholder:'Rationale for allocation…',type:'textarea'}]},
'commission':{area:'Commission processing desk',description:'Review policy-linked commission, TDS and release state before processing.',facts:[['Agent','AG-2041'],['Policy','IREC-2024-00841'],['Type','Trail'],['Status','Pending']],fields:[{label:'Commission type',value:'Trail',type:'select',options:['Upfront','Trail','Bonus']},{label:'Gross',value:'₹3,600'},{label:'TDS',value:'₹360'},{label:'Processing note',placeholder:'Commission note…',type:'textarea'}]},
'payment-links':{area:'Client collection link builder',description:'Prepare a manual EMI collection link for a selected client and delivery channels.',facts:[['Client','Aarav Mehta'],['Policy','IREC-2024-00841'],['EMI','₹10,000'],['Purpose','Manual / missed EMI']],fields:[{label:'Client',value:'Aarav Mehta',type:'select',options:['Aarav Mehta','Diya Shah','Kabir Rao']},{label:'EMI amount',value:'₹10,000'},{label:'Expiry',value:'48 hours',type:'select',options:['24 hours','48 hours','72 hours']},{label:'Delivery',value:'SMS + WhatsApp + Email',type:'select',options:['SMS + WhatsApp + Email','SMS only','Email only']}]},
'client-registry':{area:'Client service workspace',description:'Open a client record, review onboarding status and choose the next service action.',facts:[['Client','CL-20481'],['Agent','AG-2041'],['KYC','Verified'],['Policy','Active']],fields:[{label:'Client',value:'Aarav Mehta',type:'select',options:['Aarav Mehta','Diya Shah','Kabir Rao']},{label:'Service action',value:'Open client record',type:'select',options:['Open client record','Start proposal','View policy','Send payment link']},{label:'Follow-up note',placeholder:'Client interaction note…',type:'textarea'}]},
'emi-follow-up':{area:'EMI follow-up desk',description:'Record the client contact outcome and select the next recovery action.',facts:[['Client','Aarav Mehta'],['Policy','IREC-00841'],['EMI','₹10,000'],['Due','05 Sep 2026']],fields:[{label:'Contact outcome',value:'Reached',type:'select',options:['Reached','No answer','Promised payment','Wrong number']},{label:'Next action',value:'Payment link',type:'select',options:['Payment link','Reminder','Manager escalation']},{label:'Follow-up date',placeholder:'Select next follow-up date'},{label:'Call note',placeholder:'Record conversation outcome…',type:'textarea'}]},
'missed-emi-alerts':{area:'Missed EMI alert desk',description:'Review missed instalments, contact history and warning stage before sending the next notice.',facts:[['Alerts','12'],['3+ failures','2'],['At lapse risk','4'],['Today due','7']],fields:[{label:'Warning stage',value:'First reminder',type:'select',options:['First reminder','Second reminder','Lapse warning']},{label:'Channel',value:'SMS + WhatsApp',type:'select',options:['SMS + WhatsApp','SMS only','WhatsApp only']},{label:'Message note',placeholder:'Optional customer-specific note…',type:'textarea'}]},
'lapse-warnings':{area:'Lapse prevention desk',description:'Review consecutive failed EMI count and record a final recovery or escalation action.',facts:[['Policy','IREC-00821'],['Failures','3 consecutive'],['State','At lapse threshold'],['EMI','₹15,000']],fields:[{label:'Recovery route',value:'Payment link',type:'select',options:['Payment link','Manual collection','Escalate']},{label:'Customer notice',value:'Required',type:'select',options:['Required','Already sent']},{label:'Action note',placeholder:'Reason / customer response…',type:'textarea'}]},
'performance-analytics':{area:'Performance command center',description:'Review policy acquisition, EMI realization and commission performance against target.',facts:[['Policies','42'],['EMI realization','96.4%'],['Commission','₹2.84L'],['Target','82%']],fields:[{label:'Period',value:'Current month',type:'select',options:['Current month','Previous month','Quarter']},{label:'Metric focus',value:'EMI realization',type:'select',options:['EMI realization','Policies','Commission','Conversion']},{label:'Review note',placeholder:'Performance action note…',type:'textarea'}]},
'ho-notices':{area:'Head Office notices',description:'Read, acknowledge and route the latest HO communication relevant to the agent.',facts:[['Notice','HO-2026-091'],['Priority','Important'],['Issued','05 Sep 2026'],['Acknowledgement','Pending']],fields:[{label:'Acknowledgement',value:'Pending',type:'select',options:['Pending','Acknowledged']},{label:'Response note',placeholder:'Optional acknowledgement note…',type:'textarea'}]},
'document-center':{area:'Document control center',description:'Select the document, validate policy access and prepare the requested copy.',facts:[['Policy','IREC-2024-00841'],['Documents','10 types'],['Latest','Annual Benefit Summary'],['State','Ready']],fields:[{label:'Document',value:'Policy Bond',type:'select',options:['Policy Bond','Cumulative Tracker','Escalation Projection','Bank Payout Tracking','EMI Receipt','Annual Statement','Tax / Income Summary','Termination Letter','Communication Letter','Annual Benefit Summary']},{label:'Format',value:'PDF',type:'select',options:['PDF','Print']},{label:'Reason',placeholder:'Optional document request reason…',type:'textarea'}]},
'support-grievance':{area:'Support & grievance desk',description:'Create or update a support case with category, evidence, SLA and escalation path.',facts:[['Open cases','2'],['SLA','24h'],['Owner','Support Admin'],['Escalation','Ops Admin → Super Admin']],fields:[{label:'Category',value:'Payment / EMI',type:'select',options:['Payment / EMI','Policy','Yield / Benefit','Documents','KYC','Other']},{label:'Priority',value:'Normal',type:'select',options:['Low','Normal','High','Critical']},{label:'Issue',placeholder:'Describe the issue…',type:'textarea'}]},
'payments-emi':{area:'Policyholder payment center',description:'Review the EMI schedule and choose a supported payment action for an auto-debit or manual payment.',facts:[['Policy','IREC-2024-00841'],['Monthly EMI','₹10,000'],['Next due','05 Sep 2026'],['Auto-pay','Active']],fields:[{label:'Payment method',value:'Auto-pay',type:'select',options:['Auto-pay','Manual payment']},{label:'EMI amount',value:'₹10,000'},{label:'Auto-pay action',value:'Keep active',type:'select',options:['Keep active','Pause','Resume']}]},
'yield-benefits':{area:'Yield & benefit center',description:'Review the current monthly benefit statement and the Month 24 continuation or withdrawal choice.',facts:[['Current yield','₹3,600'],['Choice lock','Month 24'],['Policy month','18'],['Status','Active']],fields:[{label:'Preference',value:'Continue yield',type:'select',options:['Continue yield','Withdrawal preference']},{label:'Statement period',value:'Aug 2026',type:'select',options:['Aug 2026','Jul 2026','Jun 2026']},{label:'Note',placeholder:'Optional benefit note…',type:'textarea'}]},
'payout-tracking':{area:'Bank payout tracking',description:'Track benefit payout status from approved amount through gateway and bank confirmation.',facts:[['Payout','PAY-8821'],['Amount','₹3,600'],['Gateway','Razorpay'],['Status','Processing']],fields:[{label:'Tracking state',value:'Processing',type:'select',options:['Processing','Paid','Failed','Returned']},{label:'Bank reference',placeholder:'Enter bank reference if available'},{label:'Note',placeholder:'Tracking note…',type:'textarea'}]},
'emi-receipts':{area:'Receipt archive',description:'Filter the payment ledger and open an individual EMI receipt for download or print.',facts:[['Receipts','36'],['Latest','05 Aug 2026'],['Format','PDF'],['Status','Ready']],fields:[{label:'Receipt',value:'Aug 2026 EMI',type:'select',options:['Aug 2026 EMI','Jul 2026 EMI','Jun 2026 EMI']},{label:'Output',value:'PDF',type:'select',options:['PDF','Print']}]},
'annual-statements':{area:'Annual statement center',description:'Choose the financial year and prepare the annual policy statement.',facts:[['Policy','IREC-2024-00841'],['FY','2025–26'],['EMIs','₹1,20,000'],['Status','Ready']],fields:[{label:'Financial year',value:'FY 2025–26',type:'select',options:['FY 2025–26','FY 2024–25']},{label:'Output',value:'PDF',type:'select',options:['PDF','Download']}]},
'tax-income-summary':{area:'Tax & income summary',description:'Review the annual income/benefit summary and prepare the supported statement.',facts:[['FY','2025–26'],['Yield income','₹43,200'],['Tax statement','Ready'],['Policy','IREC-00841']],fields:[{label:'Financial year',value:'FY 2025–26',type:'select',options:['FY 2025–26','FY 2024–25']},{label:'Statement',value:'Tax / Income Summary',type:'select',options:['Tax / Income Summary','Annual Benefit Summary']}]},
'nominee-update':{area:'Nominee change request',description:'Capture nominee details, relationship and supporting evidence before submission.',facts:[['Policy','IREC-2024-00841'],['Current nominee','Priya Mehta'],['Verification','Required'],['Status','Draft']],fields:[{label:'Nominee name',placeholder:'Full legal name'},{label:'Relationship',placeholder:'Relationship to policyholder'},{label:'Share',value:'100%'},{label:'Evidence',placeholder:'Document reference'},{label:'Consent',value:'I confirm the details',type:'select',options:['I confirm the details','Needs review']}]},
'bank-change':{area:'Bank change request',description:'Update payout bank details with account verification, OTP and consent steps.',facts:[['Current bank','HDFC Bank'],['Current account','•••• 4821'],['Verification','OTP + bank check'],['Status','Draft']],fields:[{label:'Account holder',value:'Aarav Mehta'},{label:'New account',placeholder:'Enter account number'},{label:'IFSC',placeholder:'Enter IFSC'},{label:'Verification',value:'OTP + bank check',type:'select',options:['OTP + bank check','Manual review']},{label:'Consent',value:'Required',type:'select',options:['Required','Confirmed']}]},
'address-update':{area:'Address change request',description:'Capture the new address and proof document for verification.',facts:[['Policy','IREC-00841'],['Current city','Mumbai'],['Proof','Required'],['Status','Draft']],fields:[{label:'Address',placeholder:'Full correspondence address',type:'textarea'},{label:'City',placeholder:'City'},{label:'PIN code',placeholder:'PIN code'},{label:'Proof document',placeholder:'Document reference'}]},
'termination-request':{area:'Termination request desk',description:'Review termination reason, cooling-off eligibility and the resulting settlement before submission.',tone:'danger',facts:[['Policy','IREC-00841'],['Paid EMIs','₹90,000'],['Cooling-off','Eligible'],['Estimated refund','₹90,000']],fields:[{label:'Reason',value:'Personal requirement',type:'select',options:['Personal requirement','Financial need','Other']},{label:'Cooling-off',value:'Eligible',type:'select',options:['Eligible','Expired']},{label:'Settlement note',placeholder:'Reason / acknowledgement…',type:'textarea'}]},
'profile-security':{area:'Profile & security',description:'Review profile access, trusted devices and security preferences.',facts:[['Role','Policyholder'],['2FA','Enabled'],['Devices','2 trusted'],['Session','Current']],fields:[{label:'2FA',value:'Enabled',type:'select',options:['Enabled','Disabled']},{label:'Device action',value:'Review trusted devices',type:'select',options:['Review trusted devices','Sign out other devices']}]}
};

function makeProfile(role:string,screen:string,action:string):Profile{
 const a=action.trim().toLowerCase();
 const base=screenMap[screen]||{};
 const am=actionMap[a]||{};
 const area=base.area||groupFor(screen);
 const specialTone=(base.tone||am.tone||(/reject|delete|terminate|reverse|failed|danger/i.test(a)?'danger':'normal')) as Tone;
 const facts=base.facts||[['Role',role==='admin'?'Super Admin':title(role)],['Screen',title(screen)],['Action',title(a||'Review')],['Mode','Frontend workflow']];
 const fields=base.fields||[
  {label:'Record / reference',value:'DISH-2026-00841'},
  {label:'Current state',value:'Ready',type:'select',options:['Ready','Pending','Needs review','Hold']},
  {label:'Decision / next action',value:title(a||'Review'),type:'select',options:[title(a||'Review'),'Hold','Escalate']},
  {label:'Operator note',placeholder:'Record the reason, evidence or follow-up…',type:'textarea'}
 ];
 const steps=am.steps||['Review record','Validate inputs','Confirm action','Audit'];
 const primary=am.primary||title(a||'Continue');
 return {area,eyebrow:am.eyebrow||'SCREEN OPERATION',description:base.description||`Perform “${action||'review'}” for ${title(screen)} with the relevant record context and an auditable frontend confirmation flow.`,tone:specialTone,facts,fields,steps,primary,secondary:am.secondary,notice:'Frontend workflow only: confirmation updates this UI state; financial, KYC and payment mutations must be enforced server-side with authorization, idempotency and audit controls.'};
}

function Icon({tone}:{tone:Tone}){return tone==='danger'?<AlertTriangle size={19}/>:tone==='warning'?<ShieldCheck size={19}/>:<CheckCircle2 size={19}/>;}

export default function WorkflowActionModal(){
 const [modal,setModal]=useState<ModalState>(null);
 const [values,setValues]=useState<Record<string,string>>({});
 const [complete,setComplete]=useState(false);
 const [busy,setBusy]=useState(false);
 const profile=useMemo(()=>modal?makeProfile(modal.role,modal.screen,modal.action):null,[modal]);
 useEffect(()=>{
  if(typeof window==='undefined')return;
  const onClick=(e:MouseEvent)=>{
   const t=e.target as HTMLElement|null;
   if(!t||t.closest('.wamRoot')||t.closest('nav')||t.closest('aside')||t.closest('header'))return;
   const el=t.closest('button,[role="button"],a[data-workflow-action]') as HTMLElement|null;
   if(!el)return;
   const host=el.closest('.moduleScreen,.dashboard,.main,main');
   if(!host)return;
   const text=(el.getAttribute('data-workflow-action')||el.textContent||'').replace(/\s+/g,' ').trim();
   if(!text||/^(menu|logout|back|close|previous|next)$/i.test(text))return;
   if(el.tagName==='A'&&!el.getAttribute('data-workflow-action')&&el.getAttribute('href'))return;
   const {role,screen}=screenFor();
   e.preventDefault();e.stopPropagation();
   setComplete(false);setBusy(false);setValues({});setModal({role,screen,action:text});
  };
  document.addEventListener('click',onClick,true);
  return()=>document.removeEventListener('click',onClick,true);
 },[]);
 if(!modal||!profile)return null;
 const set=(label:string,v:string)=>setValues(x=>({...x,[label]:v}));
 const run=()=>{setBusy(true);window.setTimeout(()=>{setBusy(false);setComplete(true);},650);};
 return <div className="wamRoot" role="dialog" aria-modal="true" aria-label={`${profile.primary} workflow`}>
  <button className="wamBackdrop" aria-label="Close workflow" onClick={()=>setModal(null)}/>
  <section className="wamModal">
   <div className="wamHeader"><div><span>{profile.area}</span><h2>{profile.primary}</h2></div><button className="wamClose" onClick={()=>setModal(null)} aria-label="Close"><X size={17}/></button></div>
   <div className="wamBody">
    <div className={`wamSummary ${profile.tone}`}><div className="wamIcon"><Icon tone={profile.tone}/></div><div><span className="wamEyebrow">{profile.eyebrow}</span><h3>{profile.description}</h3></div></div>
    <div className="wamMiniRows">{profile.facts.map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>
    <div className="wamSteps">{profile.steps.map((s,i)=><div className={i===profile.steps.length-1?'last':''} key={s}><span>{i+1}</span><strong>{s}</strong>{i<profile.steps.length-1&&<ChevronRight size={13}/>}</div>)}</div>
    <div className="wamGrid">{profile.fields.map((f,i)=><label className={f.type==='textarea'?'wamFull':''} key={`${f.label}-${i}`}>{f.label}{f.type==='textarea'?<textarea value={values[f.label]??''} placeholder={f.placeholder} onChange={e=>set(f.label,e.target.value)}/>:f.type==='select'?<select value={values[f.label]??f.value??''} onChange={e=>set(f.label,e.target.value)}>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:<input value={values[f.label]??f.value??''} placeholder={f.placeholder} onChange={e=>set(f.label,e.target.value)}/>}</label>)}</div>
    {profile.notice&&<div className="wamInfo"><Info size={15}/><span>{profile.notice}</span></div>}
    <div className="wamAudit"><History size={15}/><div><strong>Audit trail preview</strong><span>Actor: current session · Screen: {title(modal.screen)} · Action: {modal.action} · Timestamp: now</span></div><Clock3 size={14}/></div>
    {complete&&<div className="wamInfo"><CheckCircle2 size={15}/><span><strong>{profile.primary}</strong> completed in frontend preview state. No server-side mutation was performed.</span></div>}
    <div className="wamFooter"><button className="wamSecondary" onClick={()=>setModal(null)}>{profile.secondary||'Cancel'}</button><button className={profile.tone==='danger'?'wamDanger':'wamPrimary'} disabled={busy} onClick={run}>{busy?'Processing…':complete?'Completed':profile.primary}{busy&&<span className="spin"><Clock3 size={13}/></span>}{complete&&<Download size={13}/>}</button></div>
   </div>
  </section>
 </div>;
}
